-- ===========================================================================
-- ClawCamp — Migration 0001: Baseline schema + RLS lockdown
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   Until now the live schema lived ONLY in the hosted Supabase project; there
--   was zero SQL in git. This file (a) captures the CURRENT production schema
--   as the auditable git baseline BEFORE any policy change, then (b) appends
--   the v1.0.0 lockdown statements that close the live PII/token breach.
--
-- THE BREACH (verified live via anon probe — see scripts/rls-probe.sh):
--   * The public anon key could `SELECT *` from `contacts`, returning every
--     contact's email/phone AND their `verification_token` / `magic_link_token`
--     (the contacts insert in js/supabase.js used `Prefer: return=representation`,
--     so the token was echoed straight back to the browser on every signup).
--   * The anon key could `PATCH /contacts?email=eq.<anyone>` and overwrite ANY
--     contact's row — an account-takeover / data-tamper hole.
--
-- OLD POLICY (recorded here so the diff is auditable):
--   contacts: RLS DISABLED. anon role held SELECT, INSERT, UPDATE, DELETE.
--             No row-level restriction whatsoever.
--   events:   RLS DISABLED. anon held SELECT + INSERT.
--
-- DESIGN NOTES (documented debt captured as-is, NOT changed in this migration):
--   * `contacts` is a 44-column "god table": every public form (host, sponsor,
--     staff, speaker, event, camper, startup, showcase, mentor, partner,
--     tutorial, newsletter) inserts into it, discriminated by `form_type`.
--   * Username is stuffed into `title` as the string 'username:<handle>' — see
--     dashboard/index.html saveProfile(). There is no dedicated username column.
--   * The tutorial form's "url" field is mapped to the `website` column in
--     js/supabase.js, so there is no separate `url` column.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- TABLE: contacts  (44 columns — the unified CRM "god table")
-- Column names/types reflect prod exactly (confirmed via anon probe + the
-- payloads submitted in js/supabase.js / js/nav.js and read in dashboard/).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.contacts (
  -- meta / lifecycle
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz,
  form_type          text,                 -- discriminator: host|sponsor|staff|speaker|event|camper|startup|showcase|mentor|partner|tutorial|newsletter
  status             text,                 -- free-text lifecycle/status note
  email_opt_in       boolean,              -- marketing consent captured on the form

  -- auth / verification tokens (SENSITIVE — must never reach an anon client)
  verification_token text,                 -- email-verification token, read server-side by send-verification
  magic_link_token   text,                 -- magic-link token
  verified           boolean DEFAULT false, -- flipped true server-side once the verification_token is confirmed

  -- subscription flags (toggled from the dashboard email-prefs panel)
  sub_events         boolean DEFAULT true, -- RSVP / event reminders
  sub_newsletter     boolean DEFAULT true, -- general newsletter
  sub_sponsors       boolean DEFAULT true, -- sponsor/partner updates

  -- identity / profile
  name               text,
  email              text,
  phone              text,
  city               text,
  company            text,
  title              text,                 -- also overloaded as 'username:<handle>' (dashboard profile hack)
  role               text,
  bio                text,
  linkedin           text,
  website            text,                 -- also receives the tutorial form's "url" field

  -- form-type-specific columns (seen across the js/supabase.js submissions)
  format             text,                 -- host/speaker/event format
  proposed_date      date,                 -- host/event proposed date
  venue              text,                 -- host/event venue
  about              text,                 -- host/camper "about"
  event_details      text,                 -- host/event details
  event_link         text,                 -- event registration link
  tier               text,                 -- sponsor tier
  event              text,                 -- sponsor/speaker/showcase/mentor target event
  offers             text,                 -- sponsor/speaker/mentor/partner offers
  message            text,                 -- sponsor/partner free-text message
  experience         text,                 -- staff experience
  why                text,                 -- staff "why"
  topic              text,                 -- speaker topic
  interests          text,                 -- camper interests (comma-joined)
  experience_level   text,                 -- camper experience level
  preferred_event    text,                 -- camper/startup preferred event
  stage              text,                 -- startup/showcase stage
  description        text,                 -- startup/showcase description
  pitch              text,                 -- startup/showcase pitch
  demo_ready         text,                 -- showcase demo-ready flag
  expertise          text,                 -- mentor expertise
  partnership_type   text                  -- partner partnership type
);

-- ---------------------------------------------------------------------------
-- TABLE: events  (public event directory; anon INSERT for submit-event flow)
-- Columns reflect the submit-event/index.html insert payload and the reads in
-- events/index.html, events/detail/index.html, and index.html.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text,
  event_date  date,           -- ordered by event_date.asc on the directory
  city        text,
  event_type  text,           -- in-person | virtual | hybrid (from form "format")
  description text,
  location    text,
  venue_name  text,
  time_range  text,           -- "HH:MM – HH:MM" string assembled client-side
  link        text,           -- registration / Luma URL
  notes       text,           -- stuffed: STATUS + reviewer notes + speakers/schedule/sponsors summary
  image_url   text,
  is_external boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  source      text,           -- e.g. 'submitted:<email>'
  tags        text            -- read on the directory cards
);

-- ===========================================================================
-- LOCKDOWN POLICY STATEMENTS  (v1.0.0 breach fix — the auditable change)
-- ===========================================================================
-- Each statement is commented with WHAT it does and WHY. The combined effect:
-- anon can INSERT a contact (forms keep working) but can NO LONGER read or
-- overwrite contacts; authenticated users can read/update ONLY their own row,
-- matched by the email claim in their JWT.
-- ===========================================================================

-- Turn on row-level security so the policies below are actually enforced.
-- (Was DISABLED in the old policy — every grant was effectively wide open.)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Revoke the anon SELECT grant: anon can no longer read ANY contact row,
-- which is what was leaking email/phone + verification_token/magic_link_token.
REVOKE SELECT ON public.contacts FROM anon;

-- Revoke the anon UPDATE grant: anon can no longer PATCH/overwrite contacts
-- (this is the "PATCH ?email=eq.<anyone>" account-takeover hole).
REVOKE UPDATE ON public.contacts FROM anon;

-- Keep anon INSERT so the public forms (signup, newsletter, all form_types)
-- continue to work. This is the ONLY contacts privilege anon retains.
GRANT INSERT ON public.contacts TO anon;

-- SELECT policy for the authenticated role: a logged-in user may read ONLY
-- the contact row whose `email` matches the email claim in their JWT. This
-- is what powers loadProfile()/loadPrefs() in the dashboard now that anon
-- SELECT is gone — the dashboard must call these with the user's access_token.
CREATE POLICY contacts_select_own
  ON public.contacts
  FOR SELECT
  TO authenticated
  USING (email = (auth.jwt() ->> 'email'));

-- UPDATE policy for the authenticated role: a logged-in user may update ONLY
-- their own row (matched on the JWT email), and may not relabel a row onto
-- someone else's email (WITH CHECK enforces the post-update email too). This
-- replaces the anon PATCH-by-email path used by saveProfile()/savePref().
CREATE POLICY contacts_update_own
  ON public.contacts
  FOR UPDATE
  TO authenticated
  USING (email = (auth.jwt() ->> 'email'))
  WITH CHECK (email = (auth.jwt() ->> 'email'));

-- NOTE: `events` lockdown (RLS + events.status + public-reads-approved-only)
-- is intentionally deferred to v1.2 per the roadmap. This migration only
-- closes the contacts breach; events keeps its existing anon SELECT/INSERT.
