-- ===========================================================================
-- ClawCamp — Migration 0002: Chapters table + events.chapter_id FK
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.1.0 ("chapters-are-real") turns chapters from hardcoded HTML cards into
--   real DB rows. Today chapters/index.html ships exactly two hand-coded cards
--   (a "ClawCamp San Francisco" card and an "Online Events" catch-all), with
--   FAKE social-proof numbers baked into the markup ('5' upcoming, '3' captains)
--   and a follower count read from the now-DEAD anon `contacts` SELECT path
--   (loadFollowers() in chapters/index.html fetches contacts?form_type=eq.
--   chapter_follow — that read returns nothing post-0001, because v1.0.0
--   REVOKEd anon SELECT on contacts). This migration is the data spine every
--   other v1.1.0 slice depends on: it must be committed (and applied in the
--   hosted Supabase console by an admin — anon cannot run DDL) BEFORE the table
--   exists for the chapters page / scripts slices to consume.
--
-- WHAT THIS MIGRATION DOES (in order):
--   1. CREATE public.chapters  — the real chapter directory.
--   2. ALTER public.events ADD chapter_id bigint FK -> chapters(id).
--   3. Seed chapters (SF + Online catch-all + the distinct real cities that
--      already appear in events.city).
--   4. Backfill events.chapter_id from the (kebab-cased) events.city value,
--      leaving genuinely-unmatched rows NULL pending review.
--   5. CREATE public.chapter_stats — a public-readable aggregate view that
--      exposes REAL upcoming/total event counts (replaces the fake numbers).
--   6. RLS lockdown: anon may SELECT chapters (public cards) but NOT write.
--
-- THE FK-vs-SLUG DECISION (explicitly resolved — read before "simplifying"):
--   events.chapter_id is a BIGINT FK referencing chapters(id) — deliberately
--   NOT a slug/city string. The app today guesses a chapter by city-substring
--   matching, e.g. (city||'').indexOf('san francisco') >= 0 ||
--   (city||'').indexOf('sf') >= 0 in chapters/index.html loadFollowers(). That
--   substring approach silently double-counts and drifts (any city containing
--   the letters "sf"/"san francisco" matches). A hard integer FK kills that
--   drift: a row is in exactly one chapter or in none. The human-friendly slug
--   stays ONLY on chapters.slug as the stable URL key ('sf', 'online', ...).
--
-- DESIGN NOTES (conventions inherited from 0001 — kept consistent on purpose):
--   * id uses `bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, matching
--     the contacts/events PK style in 0001 (NOT bigserial, NOT uuid).
--   * `status` is free-text + a CHECK constraint (active|forming|archived),
--     NOT a Postgres ENUM type — this matches 0001's free-text+constraint
--     convention (e.g. contacts.form_type / events.event_type are plain text)
--     and avoids the migration pain of ALTER TYPE ... ADD VALUE later.
--   * events.city in prod is uniformly kebab-cased ('san-francisco', 'oakland',
--     'online', 'new-york', ...) — verified live via the anon events SELECT and
--     mirrored by the data-city attributes in index.html / events/index.html
--     and the alias map in js/clawcamp-map.js (cityNames: 'san francisco'->'
--     san-francisco', 'sf'->'san-francisco'). The backfill below joins on that
--     kebab key but ALSO normalizes lower(trim(...)) and folds the spaced 'san
--     francisco' / bare 'sf' spellings into the single SF chapter, so a future
--     free-text submit-event row cannot create a second SF bucket.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. TABLE: chapters  (the real chapter directory; replaces hardcoded cards)
-- Column set is the v1.1.0 converged schema. Every column gets a WHAT/WHY.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chapters (
  -- meta / identity
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches contacts/events PK style in 0001
  slug           text NOT NULL UNIQUE,   -- stable URL key, e.g. 'sf', 'online' — the ONLY place a string key lives
  name           text NOT NULL,          -- display name on the card, e.g. 'ClawCamp SF, CA'

  -- geography (nullable: the 'online' catch-all has no physical location)
  city           text,                   -- human city label for the card
  region         text,                   -- state / province / region
  country        text,                   -- ISO-ish country label, e.g. 'US'
  lat            double precision,        -- map pin latitude  (from js/clawcamp-map.js cityCoords)
  lng            double precision,        -- map pin longitude (from js/clawcamp-map.js cityCoords)

  -- card presentation
  emoji          text,                   -- card glyph, e.g. '🦞' / '🌐'
  cover_gradient text,                   -- CSS gradient string used as the card cover background
  blurb          text,                   -- short description shown in the card body

  -- lifecycle
  -- Free-text + CHECK (NOT a Postgres enum) to match the 0001 convention.
  status         text NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active','forming','archived')),
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. FK column on events: events.chapter_id -> chapters.id
-- Integer FK (NOT a slug string) — see "THE FK-vs-SLUG DECISION" header note.
-- Nullable on purpose: events with no confident chapter match stay NULL and
-- are surfaced for human review rather than being force-bucketed.
-- ---------------------------------------------------------------------------
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS chapter_id bigint REFERENCES public.chapters(id);

-- Helps the chapter_stats view's per-chapter COUNT(...) and any future
-- "events for this chapter" lookups; cheap and idempotent.
CREATE INDEX IF NOT EXISTS idx_events_chapter_id ON public.events (chapter_id);

-- ---------------------------------------------------------------------------
-- 3. SEED chapters
-- (a) SF  — derived from the hardcoded 'ClawCamp SF, CA' card in
--     chapters/index.html (name/emoji/cover_gradient/blurb taken from that
--     card). status 'active'. lat/lng from js/clawcamp-map.js ('san-francisco').
-- (b) Online — the 'Other Events' / 'Online Events' catch-all card. No city.
--     status 'forming' (it is a holding bucket, not a chartered local chapter).
-- (c) One row PER DISTINCT real events.city value (the kebab keys seen live:
--     singapore, peoria, toronto, oakland, ... ), seeded status 'forming' with
--     a sensible name/emoji and coords from clawcamp-map.js. These are the
--     additional real cities the plan asks to seed so every event with a city
--     can resolve to a chapter in the backfill below.
-- Slugs are the stable kebab keys (slug == data-city key) EXCEPT San Francisco,
-- whose URL key is the short 'sf' (the backfill maps city 'san-francisco' -> 'sf').
-- INSERTs are idempotent via ON CONFLICT (slug) DO NOTHING so re-applying the
-- migration cannot create duplicate chapters.
-- ---------------------------------------------------------------------------

-- (a) San Francisco — the one fully 'active' chapter.
INSERT INTO public.chapters (slug, name, city, region, country, lat, lng, emoji, cover_gradient, blurb, status) VALUES
  ('sf', 'ClawCamp SF, CA', 'San Francisco', 'California', 'US', 37.7749, -122.4194, '🦞',
   'linear-gradient(135deg,#1a1a2e 0%,#0f3460 60%,#16213e 100%)',
   'We are a community of AI builders, learners, and creators in the Bay Area passionate about personal AI agents, OpenClaw, and hands-on collaboration.',
   'active')
ON CONFLICT (slug) DO NOTHING;

-- (b) Online — the global catch-all bucket (the 'Other Events' card).
INSERT INTO public.chapters (slug, name, city, region, country, lat, lng, emoji, cover_gradient, blurb, status) VALUES
  ('online', 'Other Events', NULL, NULL, NULL, NULL, NULL, '🌐',
   'linear-gradient(135deg,#2a2a2a,#444)',
   'Virtual events and meetups open to anyone, anywhere — not tied to a specific city chapter. Great starting point before launching your own local group.',
   'forming')
ON CONFLICT (slug) DO NOTHING;

-- (c) Real cities present in events.city (status 'forming'). lat/lng mirror
--     js/clawcamp-map.js cityCoords so the map stays consistent with chapters.
--     slug == the kebab city key so the backfill join is a straight equality.
INSERT INTO public.chapters (slug, name, city, region, country, lat, lng, emoji, cover_gradient, status) VALUES
  ('oakland',          'ClawCamp Oakland',          'Oakland',          'California',  'US',  37.8044, -122.2712, '🌲', 'linear-gradient(135deg,#1b3a2b,#0f5132)', 'forming'),
  ('new-york',         'ClawCamp New York',         'New York',         'New York',    'US',  40.7128,  -74.0060, '🗽', 'linear-gradient(135deg,#1a1a2e,#2c3e50)', 'forming'),
  ('los-angeles',      'ClawCamp Los Angeles',      'Los Angeles',      'California',  'US',  34.0522, -118.2437, '🌴', 'linear-gradient(135deg,#2c1a3e,#5a2a6e)', 'forming'),
  ('boston',           'ClawCamp Boston',           'Boston',           'Massachusetts','US', 42.3601,  -71.0589, '⚓', 'linear-gradient(135deg,#1a2e2e,#0f4646)', 'forming'),
  ('chicago',          'ClawCamp Chicago',          'Chicago',          'Illinois',    'US',  41.8781,  -87.6298, '🌬️','linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('austin',           'ClawCamp Austin',           'Austin',           'Texas',       'US',  30.2672,  -97.7431, '🤠', 'linear-gradient(135deg,#3e2a1a,#6e4a2a)', 'forming'),
  ('seattle',          'ClawCamp Seattle',          'Seattle',          'Washington',  'US',  47.6062, -122.3321, '🌧️','linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('portland',         'ClawCamp Portland',         'Portland',         'Oregon',      'US',  45.5152, -122.6784, '🌹', 'linear-gradient(135deg,#1a3320,#2a6e3a)', 'forming'),
  ('peoria',           'ClawCamp Peoria',           'Peoria',           'Illinois',    'US',  40.6936,  -89.5890, '🌽', 'linear-gradient(135deg,#33301a,#6e642a)', 'forming'),
  ('boulder',          'ClawCamp Boulder',          'Boulder',          'Colorado',    'US',  40.0150, -105.2705, '🏔️','linear-gradient(135deg,#1a2433,#3a5a6e)', 'forming'),
  ('raleigh',          'ClawCamp Raleigh',          'Raleigh',          'North Carolina','US',35.7796,  -78.6382, '🌳', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('philadelphia',     'ClawCamp Philadelphia',     'Philadelphia',     'Pennsylvania','US',  39.9526,  -75.1652, '🔔', 'linear-gradient(135deg,#2e1a1a,#6e2a2a)', 'forming'),
  ('ann-arbor',        'ClawCamp Ann Arbor',        'Ann Arbor',        'Michigan',    'US',  42.2808,  -83.7430, '〽️','linear-gradient(135deg,#2e2a1a,#6e5a2a)', 'forming'),
  ('toronto',          'ClawCamp Toronto',          'Toronto',          'Ontario',     'CA',  43.6532,  -79.3832, '🍁', 'linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('vancouver',        'ClawCamp Vancouver',        'Vancouver',        'British Columbia','CA',49.2827,-123.1207, '🏔️','linear-gradient(135deg,#1a3330,#2a6e64)', 'forming'),
  ('london',           'ClawCamp London',           'London',           'England',     'GB',  51.5074,   -0.1278, '🎡', 'linear-gradient(135deg,#1a1a2e,#2c2c54)', 'forming'),
  ('berlin',           'ClawCamp Berlin',           'Berlin',           NULL,          'DE',  52.5200,   13.4050, '🐻', 'linear-gradient(135deg,#2e2a1a,#6e642a)', 'forming'),
  ('paris',            'ClawCamp Paris',            'Paris',            NULL,          'FR',  48.8566,    2.3522, '🗼', 'linear-gradient(135deg,#1a1a2e,#3a3a6e)', 'forming'),
  ('amsterdam',        'ClawCamp Amsterdam',        'Amsterdam',        NULL,          'NL',  52.3676,    4.9041, '🚲', 'linear-gradient(135deg,#2e1f1a,#6e4a2a)', 'forming'),
  ('copenhagen',       'ClawCamp Copenhagen',       'Copenhagen',       NULL,          'DK',  55.6761,   12.5683, '🚲', 'linear-gradient(135deg,#1a2e2a,#2a6e5a)', 'forming'),
  ('stockholm',        'ClawCamp Stockholm',        'Stockholm',        NULL,          'SE',  59.3293,   18.0686, '❄️','linear-gradient(135deg,#1a2433,#3a5a8e)', 'forming'),
  ('oslo',             'ClawCamp Oslo',             'Oslo',             NULL,          'NO',  59.9139,   10.7522, '🏔️','linear-gradient(135deg,#1a2630,#2a5a7e)', 'forming'),
  ('helsinki',         'ClawCamp Helsinki',         'Helsinki',         NULL,          'FI',  60.1699,   24.9384, '🌲', 'linear-gradient(135deg,#1a2433,#2a4a7e)', 'forming'),
  ('istanbul',         'ClawCamp Istanbul',         'Istanbul',         NULL,          'TR',  41.0082,   28.9784, '🕌', 'linear-gradient(135deg,#2e1a1a,#6e3a2a)', 'forming'),
  ('ankara',           'ClawCamp Ankara',           'Ankara',           NULL,          'TR',  39.9334,   32.8597, '🇹🇷','linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('bucharest',        'ClawCamp Bucharest',        'Bucharest',        NULL,          'RO',  44.4268,   26.1025, '🏛️','linear-gradient(135deg,#1a2e2a,#2a6e54)', 'forming'),
  ('ghent',            'ClawCamp Ghent',            'Ghent',            NULL,          'BE',  51.0543,    3.7174, '🏰', 'linear-gradient(135deg,#2e2a1a,#6e5a2a)', 'forming'),
  ('toulouse',         'ClawCamp Toulouse',         'Toulouse',         NULL,          'FR',  43.6047,    1.4442, '🌹', 'linear-gradient(135deg,#2e1a24,#6e2a4a)', 'forming'),
  ('valencia',         'ClawCamp Valencia',         'Valencia',         NULL,          'ES',  39.4699,   -0.3763, '🍊', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('barcelona',        'ClawCamp Barcelona',        'Barcelona',        NULL,          'ES',  41.3874,    2.1686, '🌊', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('singapore',        'ClawCamp Singapore',        'Singapore',        NULL,          'SG',   1.3521,  103.8198, '🦁', 'linear-gradient(135deg,#1a1a2e,#0f3460)', 'forming'),
  ('tokyo',            'ClawCamp Tokyo',            'Tokyo',            NULL,          'JP',  35.6762,  139.6503, '🗾', 'linear-gradient(135deg,#2e1a24,#6e2a4a)', 'forming'),
  ('seoul',            'ClawCamp Seoul',            'Seoul',            NULL,          'KR',  37.5665,  126.9780, '🏯', 'linear-gradient(135deg,#1a2433,#2a4a7e)', 'forming'),
  ('shanghai',         'ClawCamp Shanghai',         'Shanghai',         NULL,          'CN',  31.2304,  121.4737, '🏮', 'linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('bangalore',        'ClawCamp Bangalore',        'Bangalore',        'Karnataka',   'IN',  12.9716,   77.5946, '🛕', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('delhi',            'ClawCamp Delhi',            'Delhi',            NULL,          'IN',  28.7041,   77.1025, '🛕', 'linear-gradient(135deg,#2e1a1a,#6e3a2a)', 'forming'),
  ('ho-chi-minh-city', 'ClawCamp Ho Chi Minh City', 'Ho Chi Minh City', NULL,          'VN',  10.8231,  106.6297, '🌆', 'linear-gradient(135deg,#1a2e2a,#2a6e54)', 'forming'),
  ('buenos-aires',     'ClawCamp Buenos Aires',     'Buenos Aires',     NULL,          'AR', -34.6037,  -58.3816, '💃', 'linear-gradient(135deg,#1a2433,#3a5a8e)', 'forming'),
  ('sao-paulo',        'ClawCamp São Paulo',        'São Paulo',        NULL,          'BR', -23.5505,  -46.6333, '🌃', 'linear-gradient(135deg,#1a3320,#2a6e3a)', 'forming'),
  ('rio-de-janeiro',   'ClawCamp Rio de Janeiro',   'Rio de Janeiro',   NULL,          'BR', -22.9068,  -43.1729, '🏖️','linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('belo-horizonte',   'ClawCamp Belo Horizonte',   'Belo Horizonte',   NULL,          'BR', -19.9167,  -43.9345, '⛰️','linear-gradient(135deg,#2e2a1a,#6e5a2a)', 'forming'),
  ('porto-alegre',     'ClawCamp Porto Alegre',     'Porto Alegre',     NULL,          'BR', -30.0346,  -51.2177, '🌅', 'linear-gradient(135deg,#2e1a24,#6e2a4a)', 'forming'),
  ('mexico-city',      'ClawCamp Mexico City',      'Mexico City',      NULL,          'MX',  19.4326,  -99.1332, '🌮', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('guadalajara',      'ClawCamp Guadalajara',      'Guadalajara',      NULL,          'MX',  20.6597, -103.3496, '🎺', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('bogota',           'ClawCamp Bogotá',           'Bogotá',           NULL,          'CO',   4.7110,  -74.0721, '☕', 'linear-gradient(135deg,#2e2614,#6e5a2a)', 'forming'),
  -- Long tail: the remaining distinct cities that appear in events.city today.
  -- Seeding them means the backfill resolves every CURRENT event to a chapter,
  -- leaving chapter_id = NULL only for future/unknown free-text cities. Coords
  -- mirror js/clawcamp-map.js cityCoords; emoji/gradient kept simple & on-brand.
  ('bentonville',      'ClawCamp Bentonville',      'Bentonville',      'Arkansas',     'US',  36.3729,  -94.2088, '🛒', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('kitchener',        'ClawCamp Kitchener-Waterloo','Kitchener',        'Ontario',      'CA',  43.4516,  -80.4925, '🍁', 'linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('victoria',         'ClawCamp Victoria',         'Victoria',         'British Columbia','CA',48.4284,-123.3656, '🌊', 'linear-gradient(135deg,#1a3330,#2a6e64)', 'forming'),
  ('chiang-mai',       'ClawCamp Chiang Mai',       'Chiang Mai',       NULL,           'TH',  18.7883,   98.9853, '🐘', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('virginia-beach',   'ClawCamp Virginia Beach',   'Virginia Beach',   'Virginia',     'US',  36.8529,  -75.9780, '🏖️','linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('toledo',           'ClawCamp Toledo',           'Toledo',           'Ohio',         'US',  41.6528,  -83.5379, '🌃', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('atlanta',          'ClawCamp Atlanta',          'Atlanta',          'Georgia',      'US',  33.7490,  -84.3880, '🍑', 'linear-gradient(135deg,#33181a,#6e2a2a)', 'forming'),
  ('houston',          'ClawCamp Houston',          'Houston',          'Texas',        'US',  29.7604,  -95.3698, '🚀', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('dallas',           'ClawCamp Dallas',           'Dallas',           'Texas',        'US',  32.7767,  -96.7970, '🤠', 'linear-gradient(135deg,#3e2a1a,#6e4a2a)', 'forming'),
  ('san-diego',        'ClawCamp San Diego',        'San Diego',        'California',   'US',  32.7157, -117.1611, '🏄', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('salt-lake-city',   'ClawCamp Salt Lake City',   'Salt Lake City',   'Utah',         'US',  40.7608, -111.8910, '⛰️','linear-gradient(135deg,#2e2a1a,#6e5a2a)', 'forming'),
  ('charlotte',        'ClawCamp Charlotte',        'Charlotte',        'North Carolina','US', 35.2271,  -80.8431, '🌳', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('naples',           'ClawCamp Naples',           'Naples',           'Florida',      'US',  26.1420,  -81.7948, '🌴', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('hartford',         'ClawCamp Hartford',         'Hartford',         'Connecticut',  'US',  41.7658,  -72.6734, '🏛️','linear-gradient(135deg,#1a2433,#3a5a6e)', 'forming'),
  ('stamford',         'ClawCamp Stamford',         'Stamford',         'Connecticut',  'US',  41.0534,  -73.5387, '🌃', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('berea',            'ClawCamp Berea',            'Berea',            'Kentucky',     'US',  37.5687,  -84.2963, '🌳', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('sandy-springs',    'ClawCamp Sandy Springs',    'Sandy Springs',    'Georgia',      'US',  33.9304,  -84.3733, '🍑', 'linear-gradient(135deg,#33181a,#6e2a2a)', 'forming'),
  ('rancho-cordova',   'ClawCamp Rancho Cordova',   'Rancho Cordova',   'California',   'US',  38.5891, -121.3028, '🌞', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('vero-beach',       'ClawCamp Vero Beach',       'Vero Beach',       'Florida',      'US',  27.6386,  -80.3973, '🏖️','linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('palm-beach',       'ClawCamp Palm Beach',       'Palm Beach',       'Florida',      'US',  26.7056,  -80.0364, '🌴', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('waterloo',         'ClawCamp Waterloo',         'Waterloo',         'Ontario',      'CA',  43.4643,  -80.5204, '🍁', 'linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('thunder-bay',      'ClawCamp Thunder Bay',      'Thunder Bay',      'Ontario',      'CA',  48.3809,  -89.2477, '🌲', 'linear-gradient(135deg,#1a3320,#2a6e3a)', 'forming'),
  ('mountain-view',    'ClawCamp Mountain View',    'Mountain View',    'California',   'US',  37.3861, -122.0839, '🌐', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('dublin',           'ClawCamp Dublin',           'Dublin',           NULL,           'IE',  53.3498,   -6.2603, '🍀', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('innsbruck',        'ClawCamp Innsbruck',        'Innsbruck',        NULL,           'AT',  47.2692,   11.4041, '🏔️','linear-gradient(135deg,#1a2433,#3a5a6e)', 'forming'),
  ('goteborg',         'ClawCamp Göteborg',         'Göteborg',         NULL,           'SE',  57.7089,   11.9746, '⚓', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('nairobi',          'ClawCamp Nairobi',          'Nairobi',          NULL,           'KE',  -1.2921,   36.8219, '🦁', 'linear-gradient(135deg,#33260a,#6e4a1a)', 'forming'),
  ('mumbai',           'ClawCamp Mumbai',           'Mumbai',           'Maharashtra',  'IN',  19.0760,   72.8777, '🛕', 'linear-gradient(135deg,#2e1a1a,#6e3a2a)', 'forming'),
  ('colombo',          'ClawCamp Colombo',          'Colombo',          NULL,           'LK',   6.9271,   79.8612, '🌴', 'linear-gradient(135deg,#1a2e2a,#2a6e54)', 'forming'),
  ('jakarta',          'ClawCamp Jakarta',          'Jakarta',          NULL,           'ID',  -6.2088,  106.8456, '🌆', 'linear-gradient(135deg,#33181a,#6e2a2a)', 'forming'),
  ('kota-bekasi',      'ClawCamp Bekasi',           'Bekasi',           NULL,           'ID',  -6.2383,  106.9756, '🌆', 'linear-gradient(135deg,#1a2e2a,#2a6e54)', 'forming'),
  ('taipei',           'ClawCamp Taipei',           'Taipei',           NULL,           'TW',  25.0330,  121.5654, '🏙️','linear-gradient(135deg,#1a2433,#2a4a7e)', 'forming'),
  ('hong-kong',        'ClawCamp Hong Kong',        'Hong Kong',        NULL,           'HK',  22.3193,  114.1694, '🌃', 'linear-gradient(135deg,#33181a,#a4282a)', 'forming'),
  ('dhaka',            'ClawCamp Dhaka',            'Dhaka',            NULL,           'BD',  23.8103,   90.4125, '🛺', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('melbourne',        'ClawCamp Melbourne',        'Melbourne',        'Victoria',     'AU', -37.8136,  144.9631, '☕', 'linear-gradient(135deg,#1a2433,#27496d)', 'forming'),
  ('adelaide',         'ClawCamp Adelaide',         'Adelaide',         'South Australia','AU',-34.9285, 138.6007, '🍷', 'linear-gradient(135deg,#2e1a24,#6e2a4a)', 'forming'),
  ('auckland',         'ClawCamp Auckland',         'Auckland',         NULL,           'NZ', -36.8485,  174.7633, '⛵', 'linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming'),
  ('wellington',       'ClawCamp Wellington',       'Wellington',       NULL,           'NZ', -41.2865,  174.7762, '💨', 'linear-gradient(135deg,#1a2433,#3a5a6e)', 'forming'),
  ('christchurch',     'ClawCamp Christchurch',     'Christchurch',     NULL,           'NZ', -43.5321,  172.6362, '🌳', 'linear-gradient(135deg,#1a3325,#2a6e4a)', 'forming'),
  ('dunedin',          'ClawCamp Dunedin',          'Dunedin',          NULL,           'NZ', -45.8788,  170.5028, '🏔️','linear-gradient(135deg,#1a2433,#3a5a6e)', 'forming'),
  ('manta',            'ClawCamp Manta',            'Manta',            NULL,           'EC',  -0.9500,  -80.7333, '🏖️','linear-gradient(135deg,#1a2e33,#2a5a6e)', 'forming')
ON CONFLICT (slug) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. BACKFILL events.chapter_id from events.city.
--
-- events.city is kebab-cased in prod, so the primary join is on the normalized
-- key. We normalize lower(trim(city)) defensively (in case a future anon
-- submit-event row arrives mixed-case or padded) and apply the SAME alias
-- folding js/clawcamp-map.js uses, so the spaced 'san francisco' and the bare
-- 'sf' both collapse onto the single 'sf' chapter — there is NO second SF
-- bucket. Rows whose normalized city does not match any seeded chapter are
-- LEFT chapter_id = NULL on purpose (exit criterion: null only for genuinely
-- unmatched rows), so a human can review them rather than mis-bucketing.
--
-- Done as a correlated UPDATE so it is order-independent and re-runnable:
-- re-applying only re-resolves the same key, it never reassigns a row to a
-- different chapter.
-- ---------------------------------------------------------------------------
UPDATE public.events AS e
SET chapter_id = c.id
FROM public.chapters AS c
WHERE c.slug = (
        CASE
          -- Fold every San Francisco spelling onto the single 'sf' chapter.
          WHEN lower(trim(e.city)) IN ('san-francisco', 'san francisco', 'sf')
            THEN 'sf'
          -- Treat blank/empty city as the online catch-all bucket.
          WHEN e.city IS NULL OR trim(e.city) = ''
            THEN 'online'
          -- Otherwise the kebab city key IS the chapter slug.
          ELSE lower(trim(e.city))
        END
      )
  -- Only set it where it is currently unresolved (idempotent / non-clobbering).
  AND e.chapter_id IS NULL;
-- NOTE: rows whose computed slug matches no seeded chapter simply don't join
-- here and keep chapter_id = NULL — exactly the "unmatched -> NULL" contract.

-- ---------------------------------------------------------------------------
-- 5. VIEW: chapter_stats  (public social-proof aggregate)
--
-- Replaces BOTH fake data sources on chapters/index.html:
--   * the hardcoded '5' upcoming / '3' captains strings baked into the cards, and
--   * the DEAD follower read (loadFollowers() hits contacts?form_type=eq.
--     chapter_follow, which returns nothing now that v1.0.0 REVOKEd anon SELECT
--     on contacts — see 0001).
-- Every number here is DERIVED FROM A REAL DB COUNT against events.chapter_id;
-- if a 'followers' figure is ever wanted it must likewise come from a real
-- count, NEVER from the killed anon contacts read.
--
-- Exposes one row per chapter: id, slug, upcoming_events, total_events.
-- LEFT JOIN so chapters with zero events still appear (counts = 0, not absent).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.chapter_stats AS
SELECT
  c.id                                                        AS id,
  c.slug                                                      AS slug,
  -- upcoming = future-or-today events linked to this chapter
  count(e.id) FILTER (WHERE e.event_date >= current_date)     AS upcoming_events,
  -- total = all events ever linked to this chapter
  count(e.id)                                                 AS total_events
FROM public.chapters AS c
LEFT JOIN public.events AS e ON e.chapter_id = c.id
GROUP BY c.id, c.slug;

-- ===========================================================================
-- 6. RLS + GRANTS  (anon is a hostile public client — same threat model as 0001)
-- ===========================================================================
-- The anon key ships in the browser bundle and is held by an untrusted client.
-- The public chapters page must READ chapter cards, so anon gets SELECT only.
-- anon is intentionally given NO INSERT/UPDATE/DELETE on chapters: chapter
-- creation goes through the existing 'chapter_application' form into contacts
-- and is promoted by an admin — never written directly by the browser. This
-- is the assertion target for the chapters rls-probe slice (clone of
-- scripts/rls-probe.sh): anon SELECT must succeed, anon writes must be denied.
-- ===========================================================================

-- Enforce row-level security on chapters so the SELECT policy below applies.
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

-- Grant anon the SELECT privilege (table-level) so the public site can read
-- chapter cards. No INSERT/UPDATE/DELETE grant is issued to anon — writes stay
-- closed to the hostile public client.
GRANT SELECT ON public.chapters TO anon;

-- Row-level SELECT policy: every chapter row is public (USING true). Combined
-- with the GRANT above, anon can read all chapters but nothing more.
CREATE POLICY chapters_select_public
  ON public.chapters
  FOR SELECT
  TO anon
  USING (true);

-- The chapter_stats VIEW is the public social-proof surface; anon must read it
-- to render real upcoming/total counts on the cards. A view runs with the
-- privileges of its owner, so this SELECT grant is what exposes the aggregate
-- without ever granting anon direct SELECT on the underlying events rows.
GRANT SELECT ON public.chapter_stats TO anon;
