-- ===========================================================================
-- ClawCamp — Migration 0003: events.status + structured content + lockdown
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.2.0 ("structured-content-and-moderation") does two things at once:
--     1. Replaces the leaky CLIENT-SIDE moderation hacks with a SERVER-SIDE
--        moderation gate, and
--     2. Promotes event speakers / schedule / sponsors from a hand-maintained
--        JS registry (js/event-extras.js) into real, queryable child tables.
--   This is also the deferred `events` lockdown promised in 0001: that file
--   closed the contacts breach and explicitly left `events` with anon
--   SELECT + INSERT, noting "events lockdown ... is intentionally deferred to
--   v1.2". THIS migration IS that deferred lockdown.
--
-- THE BREACHES / LEAKS THIS CLOSES (breach-avoidance reasoning):
--   * CLIENT-SIDE HIDE-LIST: events/index.html ships
--     `HIDDEN_EVENT_IDS = [171, 172]` and filters those rows out in the
--     browser AFTER fetching every row over the anon REST read. That is a
--     cosmetic hide, not a security control — anyone hitting /rest/v1/events
--     directly still receives the "hidden" rows. We replace it with an RLS
--     SELECT policy that returns ONLY status='approved' rows to anon, so the
--     hidden rows never cross the wire. (This is what lets slice D delete the
--     client hide-list safely.)
--   * STATUS-IN-NOTES: submit-event currently stuffs the literal string
--     'STATUS: submitted for review' / 'STATUS: draft' into events.notes
--     (submit-event/index.html saveEvent()). Moderation state must live in a
--     real, constrained column, not a free-text blob. We add events.status and
--     reserve events.notes for free-text REVIEWER COMMENTS only going forward.
--   * RAW ANON WRITE ON EVENTS: anon could POST straight to /rest/v1/events
--     (no validation, no moderation, client could set any column). We REVOKE
--     that grant; all writes now flow through the submit-event Edge Function,
--     which holds the service-role key and forces status='submitted'. The new
--     child tables (event_speakers/_schedule/_sponsors) are created with NO
--     anon write grant at all — the non-negotiable council rule: "never a raw
--     anon INSERT on a new public-write table; writes go through the gateway."
--
-- ADMIN WRITE / APPROVE MODEL (interim stopgap, per council notes):
--   Admin listing of submitted rows and approve/reject happens with the
--   admin's USER JWT (the `authenticated` role), gated by an admin allowlist
--   that lives in the admin page + the Edge Function for now. That allowlist
--   is the interim stopgap explicitly superseded by the v1.4 RBAC work; it is
--   intentionally NOT a DB role here. The authenticated SELECT policy below
--   lets any logged-in user (and the service role) read all rows so /admin can
--   surface non-approved submissions; anon stays restricted to approved.
--
-- CONVENTIONS INHERITED FROM 0001 / 0002 (kept consistent on purpose):
--   * id uses `bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` — matching
--     the contacts/events/chapters PK style (NOT bigserial, NOT uuid).
--   * `status` is FREE-TEXT + a CHECK constraint, NOT a Postgres ENUM type.
--     0002's header explicitly mandates this (avoids ALTER TYPE ... ADD VALUE
--     pain) and 0001 uses plain text for events.event_type / contacts.form_type.
--     The plan doc's title says "enum"; the repo convention is text+CHECK, and
--     this migration follows the repo convention.
--   * All DDL is idempotent (CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT
--     EXISTS / CREATE INDEX IF NOT EXISTS), seeds use ON CONFLICT / guarded
--     NOT EXISTS, and backfills are guarded so re-applying the migration is
--     always safe.
--
-- APPLIED OUT-OF-BAND: like 0002, this file is applied by an admin in the
--   hosted Supabase SQL console — anon cannot run DDL. scripts/rls-probe.sh is
--   the CI gate that asserts the resulting lockdown from a hostile anon client.
-- ===========================================================================

-- ===========================================================================
-- 1. events.status — the real moderation-state column (replaces STATUS-in-notes)
-- ===========================================================================
-- WHAT: add a constrained status column to events.
-- WHY:  moderation state must be a real, queryable, constrained value (the
--       anon read filter and the /admin queue both key on it), NOT the
--       free-text 'STATUS: ...' string previously jammed into events.notes.
--       Free-text + CHECK (NOT a Postgres ENUM) per the 0001/0002 convention.
--       DEFAULT 'submitted' so any future insert that forgets to set it is
--       treated as un-moderated (invisible to anon) rather than auto-public.
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'submitted'
    CHECK (status IN ('draft', 'submitted', 'approved', 'rejected'));

-- ===========================================================================
-- 2. ONE-TIME BACKFILL of status for rows that predate this column
-- ===========================================================================
-- WHAT: mark every CURRENTLY-EXISTING event row 'approved'.
-- WHY:  these rows (hand-built/imported events AND id-173) were inserted
--       before the column existed and are already live + publicly visible.
--       The ADD COLUMN above stamped them all with the DEFAULT 'submitted',
--       which the new anon RLS policy would HIDE — blanking the live site. We
--       must flip the pre-existing rows back to 'approved' as a one-time
--       backfill, guarded to `status = 'submitted'` so it only touches rows
--       carrying the just-applied default (it never resurrects a future row a
--       reviewer deliberately rejects). This UPDATE runs ONCE here, before any
--       new Edge-Function submission exists; re-applying is a no-op because the
--       AI Book Club rejection below and any real moderated rows are excluded.
UPDATE public.events
   SET status = 'approved'
 WHERE status IS NULL
    OR status = 'submitted';

-- WHAT: flip the two AI Book Club rows (ids 171, 172) to 'rejected'.
-- WHY:  events/index.html hides exactly these two ids via the client-side
--       HIDDEN_EVENT_IDS list. To make that hide a real SERVER-SIDE control
--       (and let slice D delete the client list), they must end up
--       non-approved so the anon SELECT policy filters them out over REST.
--       Guarded so it is a no-op if the rows don't exist in this environment.
UPDATE public.events
   SET status = 'rejected'
 WHERE id IN (171, 172);

-- ===========================================================================
-- 3. TABLE: event_speakers  (structured speaker rows; replaces extras.speakers)
-- ===========================================================================
-- WHAT: one row per speaker on an event.
-- WHY:  promotes the hand-kept js/event-extras.js[id].speakers array into a
--       queryable child table the detail page can read directly.
-- NAME-MAPPING NOTE: the submit-event client speaker object uses key `photo`
--   and the detail renderer reads `photo`; this column is `photo_url`. The
--   Edge Function (submit-event/index.ts) and the detail rewrite (slice C) own
--   the photo -> photo_url mapping. ON DELETE CASCADE: child rows die with the
--   parent event so no orphans linger.
CREATE TABLE IF NOT EXISTS public.event_speakers (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches 0001/0002 PK style
  event_id   bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, -- parent event; cascade kills orphans
  name       text NOT NULL,                 -- speaker display name (required)
  role       text,                          -- e.g. 'Developer Relations'
  org        text,                          -- e.g. 'Nebius'
  photo_url  text,                          -- maps from client key `photo`
  bio        text,                          -- optional long bio
  sort_order int DEFAULT 0,                 -- preserves submitted/array order
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 4. TABLE: event_schedule  (structured agenda blocks; replaces extras.schedule)
-- ===========================================================================
-- WHAT: one row per agenda/schedule block on an event.
-- WHY:  promotes js/event-extras.js[id].schedule into a queryable child table.
-- TIME-MAPPING NOTE: the client schedule object is { time, title, speaker }
--   with a SINGLE `time` string (e.g. '6:00–6:15 PM') and the detail renderer
--   reads blk.time + blk.speaker. We keep BOTH start_time and end_time columns
--   for future structure, but the Edge Function maps the client `time` string
--   into start_time and leaves end_time NULL (the detail slice reads start_time
--   as the display string). We KEEP a `speaker` column even though the plan's
--   column list omitted it: the live id-173 data and the renderer both use it,
--   and dropping it would lose data.
CREATE TABLE IF NOT EXISTS public.event_schedule (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches 0001/0002 PK style
  event_id   bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, -- parent event; cascade kills orphans
  start_time text,                          -- receives the client `time` string (display string for now)
  end_time   text,                          -- reserved for future split times; Edge Function leaves NULL
  title      text,                          -- block title, e.g. 'Welcome + Intros'
  speaker    text,                          -- KEPT: id-173 + the renderer use it (plan omitted it)
  sort_order int DEFAULT 0,                 -- preserves agenda order
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 5. TABLE: event_sponsors  (structured sponsor rows; replaces extras.sponsors)
-- ===========================================================================
-- WHAT: one row per sponsor on an event.
-- WHY:  promotes js/event-extras.js[id].sponsors into a queryable child table.
-- NAME-MAPPING NOTE: the client sponsor object is { name, logo, url, tier }.
--   We KEEP logo_url because the detail renderer reads s.logo; omitting it
--   loses parity. The Edge Function maps name -> sponsor_name, url ->
--   sponsor_url, logo -> logo_url, tier -> tier.
CREATE TABLE IF NOT EXISTS public.event_sponsors (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches 0001/0002 PK style
  event_id     bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, -- parent event; cascade kills orphans
  sponsor_name text NOT NULL,               -- maps from client key `name` (required)
  sponsor_url  text,                         -- maps from client key `url`
  tier         text,                         -- e.g. 'Gold' / 'Community'
  logo_url     text,                         -- KEPT: maps from client key `logo` (renderer reads s.logo)
  sort_order   int DEFAULT 0,                -- preserves submitted order
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 6. INDEXES
-- ===========================================================================
-- WHAT: index each child table's event_id, and index events(status).
-- WHY:  the detail page looks up child rows by event_id, and the public anon
--       read filters/sorts events on status (status = 'approved'). All cheap
--       and idempotent.
CREATE INDEX IF NOT EXISTS idx_event_speakers_event_id ON public.event_speakers (event_id);
CREATE INDEX IF NOT EXISTS idx_event_schedule_event_id ON public.event_schedule (event_id);
CREATE INDEX IF NOT EXISTS idx_event_sponsors_event_id ON public.event_sponsors (event_id);
CREATE INDEX IF NOT EXISTS idx_events_status           ON public.events (status);

-- ===========================================================================
-- 7. ONE-TIME BACKFILL of the js/event-extras.js id-173 entry into the tables
-- ===========================================================================
-- WHAT: seed the 6 speakers, 7 schedule blocks, and 1 sponsor that
--       window.EVENT_EXTRAS[173] holds today into the new child tables, with
--       event_id = 173 and sort_order preserving array order.
-- WHY:  id-173 (the June 1 Campfire) is the one richly-populated event; moving
--       its content into the tables proves the structured path end-to-end. We
--       do NOT delete or edit js/event-extras.js — the registry stays as the
--       v2.0-deferred fallback (the detail slice falls back to extras when a
--       row has no child table data, and uses extras for fullDescription, which
--       has no column here). Each block is guarded with NOT EXISTS so
--       re-applying the migration cannot duplicate the rows.
INSERT INTO public.event_speakers (event_id, name, role, org, sort_order)
SELECT * FROM (VALUES
    (173, 'Colin Lowenberg',   'Developer Relations',         'Nebius',             0),
    (173, 'Dave Nielsen',      'Advisor & Head of DevRel',    'Cognee AI',          1),
    (173, 'Marko Calvo-Cruz',  'Founder',                     'UBI Studio',         2),
    (173, 'Rayyan Zahid',      'Co-Founder',                  'Vibe Coding Nights', 3),
    (173, 'Phillip Wessels',   'Facilitator',                 'ClawCamp',           4),
    (173, 'Aditya Advani',     'Founder',                     'MoltPod',            5)
  ) AS v(event_id, name, role, org, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.event_speakers WHERE event_id = 173);

INSERT INTO public.event_schedule (event_id, start_time, title, speaker, sort_order)
SELECT * FROM (VALUES
    (173, '6:00–6:15 PM', 'Welcome + Intros',                                                        'Steven Echtman — Aiify.io', 0),
    (173, '6:15–6:30 PM', 'Talk',                                                                    'Dave Nielsen',              1),
    (173, '6:30–6:45 PM', 'Nebius — Tools for Personal Agents',                                      'Colin Lowenberg',           2),
    (173, '6:45–7:00 PM', 'Harness Your Harness',                                                    'Marko Calvo-Cruz',          3),
    (173, '7:00–7:15 PM', 'Move to Breakout Sessions',                                               '',                          4),
    (173, '7:15–8:45 PM', 'Concurrent Workshops (Second Brain, Nebius, Docker, Moltpod, VPS)',       '',                          5),
    (173, '8:45–9:00 PM', 'Wrap Up & Networking',                                                    '',                          6)
  ) AS v(event_id, start_time, title, speaker, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.event_schedule WHERE event_id = 173);

INSERT INTO public.event_sponsors (event_id, sponsor_name, sponsor_url, sort_order)
SELECT * FROM (VALUES
    (173, 'Aiify.io', 'https://aiify.io', 0)
  ) AS v(event_id, sponsor_name, sponsor_url, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.event_sponsors WHERE event_id = 173);

-- ===========================================================================
-- 8. RLS + GRANTS  (anon is a hostile public client — same threat model as
--    0001 §lockdown and 0002 §6)
-- ===========================================================================
-- The anon key ships in the browser bundle and is held by an untrusted client.
-- This section is the deferred `events` lockdown from 0001 plus the child-table
-- write closure. The combined effect:
--   * anon reads ONLY approved events (server-side moderation gate; replaces
--     the leaky client HIDDEN_EVENT_IDS),
--   * anon can NO LONGER POST to /rest/v1/events (writes go through the Edge
--     Function with the service-role key),
--   * anon may READ child rows (the detail page needs them) but can NEVER
--     write them — the non-negotiable "never a raw anon INSERT on new tables".
-- ===========================================================================

-- --- events ---------------------------------------------------------------

-- WHAT: enable RLS on events so the policies below are enforced.
-- WHY:  0001 left events with RLS effectively wide open (anon SELECT+INSERT).
--       This is the deferred lockdown; turning RLS on is step one.
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- WHAT: anon may SELECT only approved events.
-- WHY:  THIS is the server-side moderation gate. Every anon REST read of
--       events (events/index.html, events/detail, homepage index.html,
--       chapters/index.html — all of them) now returns ONLY approved rows,
--       replacing the cosmetic client-side HIDDEN_EVENT_IDS filter. Non-approved
--       rows (draft/submitted/rejected) are invisible to the hostile client.
CREATE POLICY events_select_approved
  ON public.events
  FOR SELECT
  TO anon
  USING (status = 'approved');

-- WHAT: authenticated users (incl. the service role) may SELECT every event.
-- WHY:  /admin must list submitted/draft/rejected rows to moderate them, and
--       it does so with the admin's USER JWT (the `authenticated` role; the
--       admin allowlist is enforced in the admin page + Edge Function as the
--       interim stopgap — see header). The service role used by the Edge
--       Function also needs full read to return the row it just inserted.
CREATE POLICY events_select_authenticated
  ON public.events
  FOR SELECT
  TO authenticated
  USING (true);

-- WHAT: revoke the blanket anon INSERT on events.
-- WHY:  anon must no longer POST directly to /rest/v1/events (no validation,
--       no moderation, client-settable columns). All event writes now flow
--       through the submit-event Edge Function, which holds the service-role
--       key and forces status='submitted'. This is the assertion target of the
--       rls-probe events write checks.
REVOKE INSERT ON public.events FROM anon;

-- --- event_speakers -------------------------------------------------------

-- WHAT: enable RLS; grant anon SELECT only; public read policy; NO anon write.
-- WHY:  the detail page reads child rows over the anon key, so anon needs
--       SELECT. anon gets NO INSERT/UPDATE/DELETE grant — writes are
--       service-role only via the Edge Function. This is the council rule:
--       "never a raw anon INSERT on new tables." rls-probe (d) asserts the
--       anon write is denied.
ALTER TABLE public.event_speakers ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.event_speakers TO anon;
CREATE POLICY event_speakers_select_public
  ON public.event_speakers
  FOR SELECT
  TO anon
  USING (true);

-- --- event_schedule -------------------------------------------------------

-- WHAT: enable RLS; grant anon SELECT only; public read policy; NO anon write.
-- WHY:  same posture as event_speakers — detail page reads, hostile client
--       cannot write. rls-probe (d) asserts the anon write is denied.
ALTER TABLE public.event_schedule ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.event_schedule TO anon;
CREATE POLICY event_schedule_select_public
  ON public.event_schedule
  FOR SELECT
  TO anon
  USING (true);

-- --- event_sponsors -------------------------------------------------------

-- WHAT: enable RLS; grant anon SELECT only; public read policy; NO anon write.
-- WHY:  same posture as the other child tables — detail page reads, hostile
--       client cannot write. rls-probe (d) asserts the anon write is denied.
ALTER TABLE public.event_sponsors ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.event_sponsors TO anon;
CREATE POLICY event_sponsors_select_public
  ON public.event_sponsors
  FOR SELECT
  TO anon
  USING (true);
