-- ===========================================================================
-- ClawCamp — Migration 0004: rsvps (on-site RSVP) + count RPC + lockdown
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.3.0 ("rsvp-and-identity") adds on-site RSVP to the event detail page.
--   Until now there was no way to say "I'm going" without leaving the site for
--   an external Luma/registration link. This migration creates the `rsvps`
--   table that backs that flow, plus a SECURITY DEFINER count function so the
--   detail page can show a LIVE attendee count WITHOUT exposing the roster.
--
-- THE PRODUCT MODEL (council notes — "anonymous-email-first"):
--   RSVP is anonymous-email-first: a visitor types an email (and optionally a
--   name) and is in. No login is required. OPTIONAL account linkage happens
--   "when a session exists" — if a logged-in user's id is forwarded we attach
--   it via profile_id, but it is never required. Growth attribution (UTM/ref)
--   is captured by the Edge Function from the page's query string and stored on
--   the row ("UTM capture in the Edge Function path").
--
-- THE SECURITY POSTURE / THREAT MODEL (anon is a hostile public client):
--   The anon key ships in the browser bundle and is held by an untrusted
--   client. RSVP emails are PII. So:
--     * anon gets NO INSERT grant on `rsvps`. The ONLY writer is the
--       submit-rsvp Edge Function, which holds the SERVICE-ROLE key. This is
--       the non-negotiable council rule first stated in 0003: "never a raw anon
--       INSERT on a new public-write table; writes go through the gateway." The
--       v1.3 council notes reinforce it: RSVP is anonymous-email-first but
--       routes through the v1.2 validating Edge Function (with a honeypot), NOT
--       a raw leaky anon insert.
--     * anon must NOT be able to SELECT the rsvps roster — the emails/names are
--       PII. There is NO anon SELECT grant and NO anon SELECT policy. The exit
--       criterion + scripts/rls-probe.sh (owned by the utm-probe-release slice)
--       assert: anon GET /rest/v1/rsvps?select=* returns ZERO rows / 401 / 403,
--       and anon can NEVER raw-insert an rsvp.
--     * BUT the detail page needs a LIVE attendee COUNT. A PostgREST
--       HEAD ?select=*  with  Prefer: count=exact  still requires a SELECT
--       grant for the row count to come back in Content-Range — which would
--       hand anon a readable rows path. To get a count WITHOUT leaking any PII
--       row, we expose a SECURITY DEFINER function public.rsvp_count(bigint)
--       that returns ONLY an integer (going + waitlist), and GRANT EXECUTE to
--       anon. The frontend calls it via POST /rest/v1/rpc/rsvp_count. The
--       function definer-owns the table read; anon never gets table SELECT, so
--       no email/name can ever cross the wire. (A column-limited view would
--       still risk leaking email/name if mis-scoped; the RPC is the safer,
--       recommended pattern and is what we ship.)
--     * authenticated users may SELECT only their OWN rsvps (by profile_id or
--       by JWT email) so a later dashboard can show "events you're going to".
--       The service role (the Edge Function) BYPASSES RLS for inserts/reads.
--
-- DUPLICATE PROTECTION:
--   A partial UNIQUE index (uq_rsvps_event_email_active) prevents more than one
--   ACTIVE (status <> 'cancelled') RSVP per (event_id, lower(email)). Casing is
--   normalized via lower(email) so "A@x.com" and "a@x.com" collide. Cancelled
--   rows are excluded so a guest can re-RSVP after cancelling. The Edge Function
--   surfaces the unique-violation as a friendly "you're already going" state.
--
-- CONVENTIONS INHERITED FROM 0001 / 0002 / 0003 (kept consistent on purpose):
--   * id uses `bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` — matching
--     the contacts/events/chapters PK style (NOT bigserial, NOT uuid).
--   * event_id is `bigint` to match events.id, which is
--     `bigint GENERATED BY DEFAULT AS IDENTITY` (0001 line 100). The FK type
--     MUST match or the REFERENCES would be rejected.
--   * `status` is FREE-TEXT + a CHECK constraint, NOT a Postgres ENUM type.
--     0002/0003 headers explicitly mandate this (avoids ALTER TYPE ... ADD VALUE
--     pain); 0003 did exactly this for events.status. The plan doc's title says
--     "enum"; the repo convention is text+CHECK, and this migration follows it.
--   * All DDL is idempotent (CREATE TABLE / INDEX IF NOT EXISTS, ADD COLUMN IF
--     NOT EXISTS, CREATE OR REPLACE FUNCTION) so re-applying is always safe.
--
-- APPLIED OUT-OF-BAND: like 0002 / 0003, this file is applied by an admin in
--   the hosted Supabase SQL console — anon cannot run DDL. scripts/rls-probe.sh
--   is the CI gate that asserts the resulting lockdown from a hostile anon
--   client (roster unreadable; raw anon insert denied; count RPC still works).
-- ===========================================================================

-- ===========================================================================
-- 1. TABLE: rsvps  (one row per RSVP to an event)
-- ===========================================================================
-- WHAT: an RSVP row. email is required (anonymous-email-first); name optional.
-- WHY:  backs the on-site RSVP form on events/detail. profile_id is an OPTIONAL
--       linkage to auth.users for the "session exists" case; UTM/ref columns
--       hold Growth attribution captured server-side by the Edge Function.
-- ON DELETE CASCADE on event_id: RSVPs die with their event (no orphans).
-- ON DELETE SET NULL on profile_id: deleting an auth user detaches the linkage
--   but keeps the (anonymous-email) RSVP intact, since it was never login-gated.
CREATE TABLE IF NOT EXISTS public.rsvps (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches 0001/0002/0003 PK style
  created_at   timestamptz NOT NULL DEFAULT now(),
  event_id     bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, -- FK type bigint to match events.id
  email        text NOT NULL,                 -- anonymous-email-first; always required
  name         text,                          -- optional display name
  -- Free-text + CHECK (NOT a Postgres enum) to match the 0002/0003 convention.
  status       text NOT NULL DEFAULT 'going'
    CHECK (status IN ('going', 'waitlist', 'cancelled')),
  profile_id   uuid REFERENCES auth.users(id) ON DELETE SET NULL, -- OPTIONAL account linkage; nullable, best-effort
  utm_source   text,                          -- Growth attribution, captured by the Edge Function from ?utm_source
  utm_medium   text,                          -- captured from ?utm_medium
  utm_campaign text,                          -- captured from ?utm_campaign
  ref          text                           -- captured from ?ref
);

-- ===========================================================================
-- 2. INDEXES
-- ===========================================================================
-- WHAT: index event_id, and a PARTIAL UNIQUE index on (event_id, lower(email))
--       for active (non-cancelled) rows.
-- WHY:  the live attendee-count query (and the authenticated "my rsvps" reads)
--       filter by event_id, so the plain index keeps those cheap. The partial
--       unique index enforces "one active RSVP per email per event" while still
--       allowing a cancelled row to coexist with a fresh re-RSVP. lower(email)
--       makes the uniqueness case-insensitive. All idempotent.
CREATE INDEX IF NOT EXISTS idx_rsvps_event_id ON public.rsvps (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_rsvps_event_email_active
  ON public.rsvps (event_id, lower(email))
  WHERE status <> 'cancelled';

-- ===========================================================================
-- 3. COUNT RPC: public.rsvp_count(bigint)  (PII-safe live attendee count)
-- ===========================================================================
-- WHAT: a SECURITY DEFINER function returning the number of ACTIVE attendees
--       (going + waitlist) for one event — an integer only, never a row.
-- WHY:  the detail page needs a live count, but a PostgREST count=exact HEAD
--       requires a table SELECT grant we deliberately withhold from anon (it
--       would expose the PII roster). This function runs as its DEFINER (the
--       admin/owner that creates it), so it can read public.rsvps even though
--       the CALLER (anon) has no table SELECT. It returns ONLY a bigint, so no
--       email/name can leak. anon calls it via POST /rest/v1/rpc/rsvp_count.
-- HARDENING: SECURITY DEFINER functions must pin search_path so a caller cannot
--   shadow `public`/`pg_temp` objects and trick the definer into running
--   attacker-controlled code. We set search_path = public, pg_temp explicitly.
CREATE OR REPLACE FUNCTION public.rsvp_count(event_id bigint)
  RETURNS bigint
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
  SELECT count(*)::bigint
    FROM public.rsvps r
   WHERE r.event_id = rsvp_count.event_id
     AND r.status IN ('going', 'waitlist');
$$;

-- ===========================================================================
-- 4. RLS + GRANTS  (anon is a hostile public client — same threat model as
--    0001 §lockdown, 0002 §6, and 0003 §8)
-- ===========================================================================
-- The anon key ships in the browser bundle and is held by an untrusted client.
-- The combined effect for rsvps:
--   * anon can NEVER write rsvps (no INSERT grant) — the only writer is the
--     submit-rsvp Edge Function holding the service-role key,
--   * anon can NEVER read the rsvps roster (no SELECT grant, no SELECT policy) —
--     emails/names are PII,
--   * anon CAN call rsvp_count(event_id) to get a PII-free live count,
--   * authenticated users may read ONLY their own rsvps (linkage or JWT email),
--   * the service role (Edge Function) bypasses RLS for inserts/reads.
-- ===========================================================================

-- WHAT: enable RLS on rsvps so the policy below is enforced and there is no
--       implicit wide-open access.
-- WHY:  RLS-on + no anon grant is what makes the roster unreadable to anon. The
--       service role bypasses RLS, so the Edge Function still writes/reads fine.
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- WHAT: ensure anon holds NO table privileges on rsvps (defensive REVOKE).
-- WHY:  the non-negotiable council rule — "never a raw anon INSERT on a new
--       public-write table; writes go through the gateway." We never GRANT anon
--       INSERT, and we REVOKE ALL defensively in case a default/blanket grant
--       exists in this environment. anon also gets NO SELECT, so a hostile
--       GET /rest/v1/rsvps?select=* returns zero rows / 401 / 403 — the exact
--       invariant scripts/rls-probe.sh (utm-probe-release slice) asserts.
REVOKE ALL ON public.rsvps FROM anon;

-- WHAT: authenticated users may SELECT only their OWN rsvps.
-- WHY:  lets a later dashboard show "events you're going to" without exposing
--       anyone else's PII. A row is "yours" if its profile_id matches your
--       auth.uid() (the linked-account case) OR its email matches the email
--       claim in your JWT (the anonymous-email-first case where you later log in
--       with the same address). Case-insensitive on email to match the unique
--       index. anon is unaffected (no policy applies to it; it has no grant).
CREATE POLICY rsvps_select_own
  ON public.rsvps
  FOR SELECT
  TO authenticated
  USING (
    profile_id = auth.uid()
    OR lower(email) = lower(auth.jwt() ->> 'email')
  );

-- WHAT: let anon (and authenticated) EXECUTE the count RPC.
-- WHY:  this is the ONLY rsvps-derived data anon may obtain — a PII-free
--       integer. EXECUTE on the SECURITY DEFINER function does NOT grant any
--       table access; the definer-owned read inside the function is what counts
--       the rows. This is the count path the detail page uses while the roster
--       stays sealed.
GRANT EXECUTE ON FUNCTION public.rsvp_count(bigint) TO anon, authenticated;
