-- ===========================================================================
-- ClawCamp — Migration 0005: profiles (first-class identity) + media Storage
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.3.0 ("rsvp-and-identity") stands up a FIRST-CLASS identity table and the
--   single shared Storage bucket that avatars (now) and recaps (v1.5) will share.
--   This is the structural half of the slice: it creates DB objects + Storage
--   policies ONLY. The dashboard wiring that USES this table + bucket (creating /
--   updating the CURRENT user's profile on save, uploading the avatar) is owned
--   by the dashboard-identity-and-upload slice; the rls-probe assertions that
--   verify the lockdown from a hostile anon client are owned by the
--   utm-probe-release slice. 0005 pairs with 0004 (rsvps) and does not touch it.
--
-- THE HACK THIS REPLACES (breach-avoidance / data-integrity reasoning):
--   * USERNAME-IN-TITLE: today there is NO dedicated username column. The
--     dashboard (dashboard/index.html saveProfile()) stuffs the handle into
--     contacts.title as the literal string 'username:<handle>' — see 0001 §header
--     ("Username is stuffed into `title` as the string 'username:<handle>'").
--     "Availability" is then a client-side LIKE/scan over a free-text column with
--     NO uniqueness guarantee, so two users CAN race the same @handle. We replace
--     that with a real `username citext UNIQUE` column: the DB constraint — not a
--     client check — makes "two users cannot race the same @handle" true. The
--     authenticated availability check becomes SELECT id WHERE username = ? (an
--     existence probe over the public username column only — see §3).
--
-- WHAT IS INTRODUCED FRESH IN THIS MIGRATION (none of 0001–0003 use these):
--   * citext           — needed for the case-insensitive UNIQUE username. No
--                         prior migration enables it; it is enabled ONCE here.
--   * auth.users FK     — profiles.id is keyed 1:1 to auth.users(id). 0001–0003
--                         never reference the auth schema's tables.
--   * auth.uid()        — the owner-write policies key on auth.uid(). 0001 keys
--                         contacts on the JWT EMAIL claim (auth.jwt() ->> 'email'),
--                         NOT on auth.uid(); auth.uid() is first used here.
--   * storage.objects   — the per-user-folder upload policies live on the shared
--     policies            storage.objects table. No prior migration touches the
--                         storage schema.
--
-- IDENTITY IS PUBLIC BY DESIGN — THE PII CONTRACT (read before adding columns):
--   profiles holds ONLY public identity fields (username / display_name / bio /
--   links / photo_path) so they can render on chapter + profile pages over the
--   anon key. profiles deliberately contains NO private column — no email, no
--   phone, NO verification_token / magic_link_token. Email + tokens stay in
--   `contacts`, which 0001 locked down (anon SELECT revoked; owner-only read by
--   JWT email). The exit criterion "anon cannot read another user's
--   profile-PRIVATE fields" is therefore satisfied STRUCTURALLY — there is no
--   private field in this table to leak. This is the contract the utm-probe-release
--   slice's probe relies on. >>> IF ANY SENSITIVE COLUMN IS EVER ADDED HERE, the
--   public-SELECT policy below MUST be narrowed and that column moved behind an
--   owner-only policy; do not add PII under the permissive policy. <<<
--
-- CONVENTIONS INHERITED FROM 0001 / 0002 / 0003 (kept consistent on purpose):
--   * THIS IS THE ONE uuid TABLE. The repo PK convention is
--     `bigint GENERATED BY DEFAULT AS IDENTITY` (contacts/events/chapters/the
--     0003 child tables). profiles intentionally departs: the plan mandates the
--     PK be "keyed to auth.users.id", which is a uuid, so profiles.id is
--     `uuid PRIMARY KEY REFERENCES auth.users(id)` — NOT bigint, NOT a generated
--     identity. This is the deliberate, documented exception.
--   * `username` validity is FREE-TEXT + a CHECK constraint, NOT a Postgres ENUM
--     — same posture 0002/0003 use for constrained text. The CHECK mirrors the
--     dashboard's [a-zA-Z0-9]+ handle pattern.
--   * All DDL is idempotent: CREATE EXTENSION / TABLE / INDEX IF NOT EXISTS,
--     guarded grants, and — because Postgres has NO `CREATE POLICY IF NOT EXISTS`
--     — every policy on the SHARED, PRE-EXISTING storage.objects table is wrapped
--     in `DO $$ BEGIN ... EXCEPTION WHEN duplicate_object THEN NULL; END $$;` so
--     re-applying the migration is always a no-op. (0003 used plain CREATE POLICY
--     because it created its tables fresh in the same file and could assume the
--     policies did not yet exist; storage.objects already exists with other
--     buckets' policies, so we must guard against duplicate_object here.) The
--     OPTIONAL backfill in §4 is likewise guarded so re-applying cannot abort or
--     duplicate.
--
-- APPLIED OUT-OF-BAND: like 0002/0003, this file is applied by an admin in the
--   hosted Supabase SQL console — anon cannot run DDL, and only the admin/owner
--   has rights to enable extensions, reference the auth schema, and write
--   storage.objects policies. scripts/rls-probe.sh (utm-probe-release slice) is
--   the CI gate that asserts the resulting lockdown from a hostile anon client.
-- ===========================================================================

-- ===========================================================================
-- 1. citext extension  (enabled ONCE here; no prior migration uses it)
-- ===========================================================================
-- WHAT: enable the citext (case-insensitive text) extension.
-- WHY:  the username UNIQUE constraint must be case-INSENSITIVE so '@Colin' and
--       '@colin' cannot both be claimed. citext makes the column compare/UNIQUE
--       case-insensitively WITHOUT a separate lower() expression index. This is
--       the first migration to need it, so it is enabled here; IF NOT EXISTS
--       makes re-applying a no-op.
CREATE EXTENSION IF NOT EXISTS citext;

-- ===========================================================================
-- 2. TABLE: profiles  (first-class identity, keyed 1:1 to the auth user)
-- ===========================================================================
-- WHAT: one identity row per Supabase auth user.
-- WHY:  promotes identity out of the contacts.title='username:<handle>' hack
--       (see header) into a real, queryable, uniqueness-enforced table.
-- KEY/PK NOTE: id is `uuid REFERENCES auth.users(id) ON DELETE CASCADE` — this is
--   the ONE uuid table (the repo PK convention is bigint identity; the plan
--   mandates "keyed to auth.users.id", a uuid, so we depart deliberately). The
--   1:1 FK means a profile cannot exist without its auth user, and ON DELETE
--   CASCADE means deleting the auth user removes the profile (so no DELETE grant
--   is needed below). NO PRIVATE COLUMNS live here — see the PII contract in the
--   header; email + tokens stay in contacts.
CREATE TABLE IF NOT EXISTS public.profiles (
  id           uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, -- 1:1 to the Supabase auth user; the one uuid PK (plan: "keyed to auth.users.id")
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz,                              -- set by the dashboard slice on save; nullable until first edit
  username     citext UNIQUE                             -- THE real uniqueness constraint replacing the contacts.title='username:' LIKE hack; citext = case-insensitive. UNIQUE already creates the lookup index (no separate index needed).
                 CHECK (username ~ '^[A-Za-z0-9]+$' AND char_length(username) BETWEEN 1 AND 30), -- mirrors the dashboard's [a-zA-Z0-9]+ handle pattern + a sane 1..30 length
  display_name text,                                     -- public display name (renders on chapter/profile pages)
  bio          text,                                     -- public short bio
  links        jsonb NOT NULL DEFAULT '{}'::jsonb,       -- structured public links (linkedin/website/etc.) per the plan ("links jsonb"); defaults to {} so a row always has a valid object
  photo_path   text                                      -- Storage object path UNDER the user's folder in the 'media' bucket (e.g. '<uid>/avatar.jpg') — a PATH, NOT a public URL; the client derives the public URL from this path
);

-- NOTE on indexes: the `username citext UNIQUE` above ALREADY creates the unique
-- B-tree index used by the availability existence check, and citext makes it
-- case-insensitive on its own. A separate CREATE INDEX ... lower(username) would
-- be redundant, so none is added here.

-- ===========================================================================
-- 3. RLS + GRANTS on profiles  (anon is a hostile public client — same threat
--    model as 0001 §lockdown and 0003 §8)
-- ===========================================================================
-- The anon key ships in the browser bundle and is held by an untrusted client.
-- profiles is PUBLIC-SELECT but PII-SAFE (see the header's PII contract): every
-- column is public identity, so a permissive read policy is correct AND safe.
-- Writes are OWNER-ONLY: an authenticated user may insert/update only their own
-- row (id = auth.uid()); anon gets NO write grant at all. The combined effect:
--   * anyone (anon + authenticated) may READ any profile — usernames /
--     display_name / bio / links / photo_path render on chapter + profile pages,
--   * an authenticated user may WRITE only their OWN row,
--   * anon may NEVER write a profile,
--   * there is NO private field to leak (structural guarantee — see header).
-- ===========================================================================

-- WHAT: enable RLS on profiles so the policies below are enforced.
-- WHY:  without RLS the table grants would govern access directly; we want
--       per-row owner-write enforcement, so RLS is step one (same as 0001/0003).
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- WHAT: grant anon + authenticated SELECT, with a permissive read policy.
-- WHY:  the plan calls for "public-SELECT RLS" so identity renders on chapter /
--       profile pages over the anon key. USING (true) is correct here precisely
--       BECAUSE the table is PII-safe (header contract): no private column exists
--       to expose. This is also what powers the authenticated availability check
--       that replaces the broken contacts.title='username:' scan — SELECT id
--       WHERE username = ? is an EXISTENCE probe that reads across all rows, and
--       that is intentional and safe because only the public username column is
--       ever exposed, never private data.
GRANT SELECT ON public.profiles TO anon, authenticated;
CREATE POLICY profiles_select_public
  ON public.profiles
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- WHAT: grant ONLY authenticated INSERT + UPDATE (no anon write; no DELETE).
-- WHY:  identity is written by the signed-in owner from the dashboard. anon gets
--       NO write grant (a hostile anon client cannot create or alter any
--       profile). No DELETE grant: profiles.id ON DELETE CASCADE from auth.users
--       handles row removal when the account is deleted, so there is no
--       client-facing delete path to expose.
GRANT INSERT, UPDATE ON public.profiles TO authenticated;

-- WHAT: an authenticated user may INSERT only their OWN row.
-- WHY:  WITH CHECK (id = auth.uid()) binds the new row's PK to the caller's auth
--       uid, so a user cannot create a profile under someone else's id. This is
--       how the dashboard slice creates the CURRENT user's profile on save.
CREATE POLICY profiles_insert_own
  ON public.profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (id = auth.uid());

-- WHAT: an authenticated user may UPDATE only their OWN row.
-- WHY:  USING (id = auth.uid()) restricts WHICH rows are visible to update, and
--       WITH CHECK (id = auth.uid()) forbids re-keying the row onto someone
--       else's id (same belt-and-suspenders posture as 0001's contacts_update_own
--       on the JWT email). The UNIQUE on username still guarantees that even a
--       legitimate owner cannot claim a handle another row already holds — the
--       race-proof guarantee the exit criteria demand.
CREATE POLICY profiles_update_own
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- ===========================================================================
-- 4. (OPTIONAL) ONE-TIME, GUARDED backfill of existing identity into profiles
-- ===========================================================================
-- WHAT: best-effort seed of a profile per auth.users row by joining contacts on
--       lower(email), pulling name -> display_name, bio -> bio, building links
--       jsonb from contacts.linkedin / contacts.website, and stripping the
--       'username:' prefix from contacts.title -> username.
-- WHY:  the plan mentions migrating signed-in users' name/bio/links and the
--       contacts title='username:' handle into profiles. This is INTENTIONALLY
--       OPTIONAL and fully GUARDED for several reasons:
--         * profiles.id is auth.users(id) but contacts is keyed by EMAIL, so the
--           only join available is lower(email) = lower(auth.users.email); there
--           is no guaranteed clean mapping, and contacts rows without a matching
--           auth user simply do not backfill (correct — they have no identity).
--         * A duplicate / colliding derived username must NOT abort the
--           migration: ON CONFLICT (id) DO NOTHING makes the per-user insert
--           idempotent, and the NOT EXISTS username-collision guard skips any row
--           whose derived handle is already taken (the first claimant wins; the
--           rest set their handle later from the dashboard). The username CHECK
--           also rejects malformed handles, so only [A-Za-z0-9]{1,30} values land.
--         * Re-applying is a no-op (ON CONFLICT (id) DO NOTHING).
--       The dashboard slice creates/updates the CURRENT user's profile on save
--       regardless, so the system of record flips forward even if this backfill
--       matches nothing. >>> IF the hosted SQL console's role cannot read the
--       auth schema in your environment, COMMENT OUT this block and run it later
--       as a documented manual step — never let an uncertain auth read abort the
--       structural DDL above. <<<
--
-- This block is wrapped in DO $$ ... $$ and tolerates the auth.users table being
-- unreadable / absent by swallowing insufficient_privilege + undefined_table, so
-- a permissions/visibility difference between environments can never abort the
-- migration that already created the table and policies above.
DO $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, bio, links, created_at)
  SELECT
    u.id,
    -- derive a handle ONLY from a well-formed 'username:<handle>' title, else NULL
    CASE
      WHEN c.title ~ '^username:[A-Za-z0-9]{1,30}$'
        THEN substring(c.title FROM 'username:([A-Za-z0-9]{1,30})$')
      ELSE NULL
    END                                                   AS username,
    c.name                                                AS display_name,
    c.bio                                                 AS bio,
    -- build a links object from only the present link columns; {} when both null
    ( '{}'::jsonb
      || CASE WHEN c.linkedin IS NOT NULL AND c.linkedin <> '' THEN jsonb_build_object('linkedin', c.linkedin) ELSE '{}'::jsonb END
      || CASE WHEN c.website  IS NOT NULL AND c.website  <> '' THEN jsonb_build_object('website',  c.website)  ELSE '{}'::jsonb END
    )                                                     AS links,
    now()                                                 AS created_at
  FROM auth.users u
  -- pick at most one contacts row per auth user (lowest id wins on duplicates)
  LEFT JOIN LATERAL (
    SELECT cc.*
      FROM public.contacts cc
     WHERE lower(cc.email) = lower(u.email)
     ORDER BY cc.id
     LIMIT 1
  ) c ON true
  -- skip any row whose derived handle is ALREADY taken (first claimant wins);
  -- a NULL derived username never collides (citext UNIQUE permits many NULLs)
  WHERE NOT EXISTS (
    SELECT 1
      FROM public.profiles p
     WHERE c.title ~ '^username:[A-Za-z0-9]{1,30}$'
       AND p.username = substring(c.title FROM 'username:([A-Za-z0-9]{1,30})$')
  )
  ON CONFLICT (id) DO NOTHING;   -- per-user idempotent: re-applying inserts nothing
EXCEPTION
  WHEN insufficient_privilege OR undefined_table THEN
    -- auth schema not readable / not present in this environment: skip the
    -- backfill rather than abort. Run it later as a documented manual step.
    RAISE NOTICE 'profiles backfill skipped (auth.users not accessible here); run manually if desired';
END $$;

-- ===========================================================================
-- 5. STORAGE: the single shared 'media' bucket + per-user-folder RLS
-- ===========================================================================
-- WHAT: provision ONE bucket named exactly 'media' and lock storage.objects so
--       a user may only write UNDER a top-level folder equal to their auth.uid().
-- WHY:  council coordination ask — avatars (now) and recaps (v1.5) share ONE
--       bucket, 'media'. The bucket is PUBLIC (public = true) so avatars render
--       via a plain public URL with no signing. The file_size_limit (5 MB) +
--       allowed_mime_types give the SERVER-SIDE content-type/size validation the
--       plan + exit criteria require ("an anon or cross-user upload is rejected by
--       bucket RLS and content validation") — the dashboard hint already promises
--       JPG/PNG/GIF/WebP up to 5 MB, mirrored here on the SERVER so the client
--       cannot bypass it.
-- NET INVARIANT (asserted later by the utm-probe-release slice): anon cannot
--   write to ANY folder, and an authenticated user cannot write to another user's
--   folder (path prefix != their uid).
-- IDEMPOTENCY NOTE: Postgres has NO `CREATE POLICY IF NOT EXISTS`, and
--   storage.objects is a SHARED, pre-existing table that already carries other
--   policies — so unlike 0003 (which created its tables fresh), each policy here
--   is wrapped in DO $$ ... EXCEPTION WHEN duplicate_object THEN NULL; END $$; so
--   re-applying the migration is a no-op. The bucket INSERT uses ON CONFLICT (id)
--   DO NOTHING for the same reason.

-- WHAT: create the 'media' bucket idempotently.
-- WHY:  public = true (avatars render without signing); 5 MB size cap +
--       image-only MIME allowlist enforce server-side validation. ON CONFLICT
--       (id) DO NOTHING makes re-applying a no-op and never clobbers an
--       already-tuned bucket.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('media', 'media', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp'])
ON CONFLICT (id) DO NOTHING;

-- --- storage.objects: per-user-folder write policies (media bucket only) -----
-- The convention: the FIRST path segment of the object name must equal the
-- caller's auth.uid(). storage.foldername(name) returns the path segments as a
-- text[]; element [1] is the top-level folder. Scoping every policy to
-- bucket_id = 'media' leaves other buckets' policies untouched.

-- WHAT: authenticated users may INSERT (upload) only into their own uid folder.
-- WHY:  WITH CHECK ties the upload path prefix to auth.uid(), so a user cannot
--       write into another user's folder, and anon (no policy/grant) cannot
--       upload at all. This is the avatar-upload path the dashboard slice uses.
DO $$
BEGIN
  CREATE POLICY media_insert_own
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (
      bucket_id = 'media'
      AND (storage.foldername(name))[1] = auth.uid()::text
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- WHAT: authenticated users may UPDATE only objects in their own uid folder.
-- WHY:  USING restricts which objects are visible to update; WITH CHECK forbids
--       moving an object out of (or into) someone else's folder. Lets a user
--       replace their own avatar, never another user's.
DO $$
BEGIN
  CREATE POLICY media_update_own
    ON storage.objects
    FOR UPDATE
    TO authenticated
    USING (
      bucket_id = 'media'
      AND (storage.foldername(name))[1] = auth.uid()::text
    )
    WITH CHECK (
      bucket_id = 'media'
      AND (storage.foldername(name))[1] = auth.uid()::text
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- WHAT: authenticated users may DELETE only objects in their own uid folder.
-- WHY:  USING ties deletion to auth.uid(), so a user can remove their own avatar
--       but never another user's object. anon has no delete path.
DO $$
BEGIN
  CREATE POLICY media_delete_own
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (
      bucket_id = 'media'
      AND (storage.foldername(name))[1] = auth.uid()::text
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- WHAT: explicit public READ policy for the media bucket.
-- WHY:  the bucket is public = true, so reads already work without signing; we
--       add an EXPLICIT SELECT policy (anon + authenticated, scoped to the media
--       bucket) so the read posture is legible in the policy list and does not
--       depend solely on the bucket flag. Read is intentionally open — avatars
--       are public identity (same PII posture as the profiles table).
DO $$
BEGIN
  CREATE POLICY media_read_public
    ON storage.objects
    FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'media');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
