-- ===========================================================================
-- ClawCamp — Migration 0006: memberships (RBAC) + role helpers + write gates
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.4.0 ("rbac-and-captains-console") replaces the v1.2 hardcoded
--   ADMIN_EMAILS allowlist (admin/index.html line ~219, currently
--   ['collin@dabl.club']) with REAL, server-enforced roles, and introduces the
--   captain role so a chapter organizer can approve/reject/edit ONLY their own
--   chapter's events + roster WITHOUT being a global admin. This is the FIRST
--   v1.4 slice and the data spine every other v1.4 slice depends on: the
--   captain console, the dashboard "my roles" surface, and the chapter-edit UI
--   all read/enforce against the objects defined here. Those slices touch
--   DISJOINT files (HTML / js / Edge Functions); this migration touches ONLY
--   the DB + the rls-probe + the data-model doc.
--
-- THE ROLE MODEL (council notes — "roles are data, enforced server-side"):
--   A `memberships` row grants exactly one role ('member' | 'captain' |
--   'admin') to one auth user within one chapter. Authorization is decided
--   SERVER-SIDE by two SECURITY DEFINER helpers (is_chapter_role / is_claw_admin)
--   used inside RLS policies — NEVER by a client-side role check, which is
--   cosmetic and trivially forged. A 'captain' membership authorizes writes
--   scoped to THAT chapter (its events, its chapter row, its roster); an 'admin'
--   membership is a GLOBAL grant (chapter-independent — see is_claw_admin) that
--   replaces the ADMIN_EMAILS allowlist outright.
--
-- THE SECURITY POSTURE / THREAT MODEL (anon is a hostile public client — same
--   paragraph as 0004 §4 and 0005 §3):
--   The anon key ships in the browser bundle and is held by an untrusted client.
--   For memberships specifically:
--     * NO-SELF-PROMOTE is the headline exit criterion: a `member` (or anon)
--       must NOT be able to grant themselves `captain`/`admin`. We achieve this
--       STRUCTURALLY — authenticated gets SELECT-only on memberships (read your
--       own rows) and NO write grant / NO write policy at all. Roles are written
--       ONLY by an admin in the SQL console (or, later, a service-role gateway),
--       never by the browser. See §3.
--     * Role HELPERS are SECURITY DEFINER so an RLS policy can ask "does the
--       caller hold role X on chapter N?" by reading memberships even though the
--       caller has no broad SELECT over other users' rows. They pin search_path
--       (= public, pg_temp) exactly like rsvp_count in 0004 so a caller cannot
--       shadow public objects and trick the definer into running attacker code.
--     * The events / chapters UPDATE gates (§4, §5) and the rsvps captain-SELECT
--       (§6) are the policies these helpers unlock. A hostile anon client holds
--       no membership, so every helper returns false for it and every gated
--       write/read is denied — the property scripts/rls-probe.sh asserts.
--
-- CONVENTIONS INHERITED FROM 0001–0005 (kept consistent on purpose):
--   * id uses `bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` — matching
--     the contacts/events/chapters/rsvps PK style (NOT bigserial, NOT uuid).
--   * profile_id is `uuid REFERENCES auth.users(id)` — the SAME FK style as
--     rsvps.profile_id (0004) / profiles.id (0005); chapter_id is `bigint` to
--     match chapters.id (0002), so the REFERENCES type lines up.
--   * `role` is FREE-TEXT + a CHECK constraint, NOT a Postgres ENUM type. The
--     0002/0003/0004 headers explicitly mandate this (avoids ALTER TYPE ... ADD
--     VALUE pain); this migration follows that convention.
--   * Role helpers SET search_path = public, pg_temp — the SAME hardening as
--     rsvp_count in 0004.
--   * All DDL is idempotent (CREATE TABLE / INDEX IF NOT EXISTS, CREATE OR
--     REPLACE FUNCTION, guarded grants, and — because Postgres has NO `CREATE
--     POLICY IF NOT EXISTS` — every CREATE POLICY is wrapped in
--     `DO $$ BEGIN ... EXCEPTION WHEN duplicate_object THEN NULL; END $$;`, the
--     same guard 0005 uses for storage.objects policies) so re-applying is
--     always a safe no-op. The OPTIONAL backfill in §7 is likewise guarded.
--
-- APPLIED OUT-OF-BAND: like 0002–0005, this file is applied by an admin in the
--   hosted Supabase SQL console — anon cannot run DDL, and only the admin/owner
--   may create SECURITY DEFINER functions and reference the auth schema.
--   scripts/rls-probe.sh is the CI gate that asserts the resulting lockdown from
--   a hostile anon client (no self-grant of a role; roles not world-readable;
--   the events UPDATE policy does not leak write to anon).
-- ===========================================================================

-- ===========================================================================
-- 1. TABLE: memberships  (one row = one role for one user in one chapter)
-- ===========================================================================
-- WHAT: a role grant. profile_id is the auth user; chapter_id the chapter;
--       role is one of member|captain|admin. UNIQUE (profile_id, chapter_id)
--       means a user has AT MOST ONE membership row per chapter.
-- WHY:  this is the table that makes roles DATA (server-enforced via the helpers
--       + policies below) instead of a hardcoded client allowlist. ON DELETE
--       CASCADE on BOTH FKs: a membership dies with its auth user (account
--       deletion) and with its chapter (chapter removal) — no orphan grants.
CREATE TABLE IF NOT EXISTS public.memberships (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches contacts/events/chapters/rsvps PK style (NOT uuid, NOT bigserial)
  created_at  timestamptz NOT NULL DEFAULT now(),
  profile_id  uuid   NOT NULL REFERENCES auth.users(id)     ON DELETE CASCADE, -- the auth user; same FK style as rsvps.profile_id / profiles.id
  chapter_id  bigint NOT NULL REFERENCES public.chapters(id) ON DELETE CASCADE, -- bigint to match chapters.id (0002)
  -- Free-text + CHECK (NOT a Postgres enum) to match the 0002/0003/0004
  -- convention — keeps adding a future role a data change, not an ALTER TYPE.
  role        text NOT NULL DEFAULT 'member'
                CHECK (role IN ('member', 'captain', 'admin')),
  -- At most one membership row per (user, chapter): a user cannot hold two
  -- conflicting roles in the same chapter. (A global admin grant is modeled as
  -- an admin-role row in SOME chapter; is_claw_admin() ignores which one.)
  UNIQUE (profile_id, chapter_id)
);

-- ===========================================================================
-- 2. INDEXES
-- ===========================================================================
-- WHAT: index chapter_id and profile_id.
-- WHY:  the role helpers (§2.5) and policies filter by chapter_id (and by
--       auth.uid() => profile_id), and the dashboard reads a user's own rows by
--       profile_id; both indexes keep those lookups cheap. The UNIQUE
--       (profile_id, chapter_id) above already provides a (profile_id, ...)
--       composite, but an explicit single-column index on each keeps the two
--       hot access paths (by chapter, by user) direct and legible. Idempotent.
CREATE INDEX IF NOT EXISTS idx_memberships_chapter_id ON public.memberships (chapter_id);
CREATE INDEX IF NOT EXISTS idx_memberships_profile_id ON public.memberships (profile_id);

-- ===========================================================================
-- 2.5 ROLE HELPERS: public.is_chapter_role(bigint, text) + public.is_claw_admin()
-- ===========================================================================
-- WHAT: two SECURITY DEFINER predicates the RLS policies call to authorize a
--       write/read for the CURRENT caller (auth.uid()):
--         * is_chapter_role(p_chapter_id, p_role) -> true iff the caller holds
--           a membership with exactly p_role on p_chapter_id.
--         * is_claw_admin()                       -> true iff the caller holds
--           ANY membership row with role='admin' (a GLOBAL admin grant,
--           chapter-independent). This is the direct replacement for the v1.2
--           hardcoded ADMIN_EMAILS allowlist (admin/index.html ~line 219, whose
--           own comment says "Keep this in sync with the allowlist in the events
--           RLS policy" — that linkage is now THIS function instead of a copied
--           email list).
-- WHY SECURITY DEFINER: an ordinary authenticated caller has SELECT only on its
--   OWN memberships rows (§3), so it cannot itself evaluate "does user U hold
--   role R on chapter C" across the table. These functions run as their DEFINER
--   (the admin/owner that creates them) so they can read all of memberships to
--   answer the predicate, while returning ONLY a boolean — no membership row
--   ever crosses the wire. This is the exact pattern rsvp_count (0004) uses to
--   return a count without exposing the roster.
-- HARDENING: SECURITY DEFINER functions MUST pin search_path so a caller cannot
--   shadow `public`/`pg_temp` objects and trick the definer into running
--   attacker-controlled code; we SET search_path = public, pg_temp explicitly,
--   identical to rsvp_count in 0004.
-- NOTE: both are STABLE (they read tables, do not mutate) and reference
--   auth.uid(); for an anon caller auth.uid() is NULL, so no membership matches
--   and both return false — the hostile-client default-deny.

CREATE OR REPLACE FUNCTION public.is_chapter_role(p_chapter_id bigint, p_role text)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
      FROM public.memberships m
     WHERE m.profile_id = auth.uid()
       AND m.chapter_id = p_chapter_id
       AND m.role       = p_role
  );
$$;

CREATE OR REPLACE FUNCTION public.is_claw_admin()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
      FROM public.memberships m
     WHERE m.profile_id = auth.uid()
       AND m.role       = 'admin'
  );
$$;

-- WHAT: let anon + authenticated EXECUTE both helpers.
-- WHY:  RLS policies (and the client, harmlessly) call these to decide
--       authorization. EXECUTE on a SECURITY DEFINER function grants NO table
--       access — the definer-owned read INSIDE the function is what touches
--       memberships; the caller only ever receives a boolean. (Same grant
--       reasoning as the rsvp_count GRANT in 0004.) Granting anon EXECUTE is
--       safe and convenient: for an anon caller auth.uid() is NULL, so both
--       always return false.
GRANT EXECUTE ON FUNCTION public.is_chapter_role(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_claw_admin()               TO anon, authenticated;

-- ===========================================================================
-- 3. RLS + GRANTS on memberships  (anon is a hostile public client — same
--    threat model as 0004 §4 / 0005 §3)
-- ===========================================================================
-- >>> NO-SELF-PROMOTE — THE HEADLINE EXIT CRITERION <<<
--   "A member cannot grant themselves captain." We make that TRUE structurally:
--   authenticated may SELECT only its OWN membership rows, and gets NO INSERT /
--   UPDATE / DELETE grant and NO write policy whatsoever. Roles are written ONLY
--   by an admin in the hosted SQL console (or, later, a service-role gateway
--   Edge Function), NEVER by the browser. A member therefore cannot INSERT an
--   admin/captain row for themselves, cannot UPDATE their own row's `role`, and
--   anon cannot write at all. scripts/rls-probe.sh asserts assertion (j): an
--   anon POST to /rest/v1/memberships (e.g. role:'captain') is DENIED — any 2xx
--   would mean a hostile client could self-grant a role and is a hard FAIL.
--   The combined effect:
--     * anon can NEVER read or write memberships (no grant, no policy),
--     * authenticated may READ only its OWN rows (for the dashboard "my roles"),
--     * NOBODY writes memberships via the client — roles are granted out-of-band,
--     * the service role (a future gateway) bypasses RLS for admin grants.
-- ===========================================================================

-- WHAT: enable RLS on memberships so the SELECT policy below is enforced and
--       there is no implicit wide-open access.
-- WHY:  RLS-on + SELECT-own + no write policy is what makes "roles are not
--       client-writable and not world-readable" true.
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;

-- WHAT: ensure anon holds NO table privileges on memberships (defensive REVOKE).
-- WHY:  roles must never be readable or writable by the hostile public client.
--       We never GRANT anon anything here, and REVOKE ALL defensively in case a
--       default/blanket grant exists in this environment. anon thus has no
--       SELECT (assertion (k): a hostile GET returns zero rows / 401 / 403) and
--       no write (assertion (j): a hostile POST is denied).
REVOKE ALL ON public.memberships FROM anon;

-- WHAT: authenticated may SELECT only their OWN membership rows; NO write grant.
-- WHY:  the dashboard shows the signed-in user "the chapters you captain /
--       admin" by reading WHERE profile_id = auth.uid(). We deliberately grant
--       ONLY SELECT — no INSERT/UPDATE/DELETE — so a member cannot self-promote.
GRANT SELECT ON public.memberships TO authenticated;

-- WHAT: row-level SELECT policy — a user sees ONLY their own membership rows.
-- WHY:  profile_id = auth.uid() scopes reads to the caller's own grants, so one
--       user cannot enumerate another user's roles. (Captains do NOT need to
--       read the full member list for THIS feature; if a future slice wants a
--       captain-visible roster of members, it adds a SEPARATE narrowly-scoped
--       SELECT policy — it must NOT widen this one.)
DO $$
BEGIN
  CREATE POLICY memberships_select_own
    ON public.memberships
    FOR SELECT
    TO authenticated
    USING (profile_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- >>> INTENTIONALLY NO authenticated INSERT/UPDATE/DELETE GRANT AND NO WRITE
--     POLICY ON memberships. <<<
-- This is the no-self-promote exit criterion. Do NOT add a client write path
-- here. Roles are granted by an admin in the SQL console (§7 seeds the first
-- one) or, later, a service-role gateway that bypasses RLS. rls-probe assertion
-- (j) asserts a hostile anon/self write is denied; adding a write policy here
-- would regress that guarantee.

-- ===========================================================================
-- 4. events UPDATE gate  (THE linchpin policy of this migration — read this)
-- ===========================================================================
-- THE STATE TODAY: migration 0003 (§8) ENABLEd RLS on public.events and added
--   SELECT policies (events_select_approved for anon, plus an authenticated
--   read), but defined NO UPDATE policy. With RLS enabled and no UPDATE policy,
--   PostgreSQL denies ALL updates at the policy layer — so today the v1.2 /admin
--   approve/reject PATCH only "works" because the admin path uses... (whatever
--   it used). After THIS migration, the single policy below is the ONE thing
--   that authorizes an UPDATE to events, for BOTH roles:
--     * a GLOBAL admin (is_claw_admin()) — this is what now authorizes the v1.2
--       /admin approve/reject PATCH, replacing the ADMIN_EMAILS check, AND
--     * a CAPTAIN of the event's own chapter (is_chapter_role(chapter_id,
--       'captain')) — this is what authorizes the new captain console's
--       approve / reject / edit of events whose events.chapter_id matches a
--       chapter the caller captains.
--   The chapter_id IS NOT NULL guard means an event with no chapter is editable
--   only by a global admin (a captain cannot claim an unassigned event).
--   USING (visibility of the target row) and WITH CHECK (validity of the
--   post-update row) use the SAME predicate so a captain can neither edit an
--   event outside their chapter NOR re-assign an event INTO/OUT OF their chapter
--   to smuggle a write — both directions are checked.
-- EXIT CRITERION (asserted by rls-probe assertion (m)): a hostile ANON PATCH of
--   events?id=eq.<n> (e.g. {"status":"approved"}) is DENIED — this policy is
--   TO authenticated, and both helpers return false for anon, so the gate never
--   leaks write access to the public client. An authenticated captain PATCHing
--   ANOTHER chapter's event is likewise rejected (is_chapter_role is false for
--   that chapter) — verified at the app layer / by the console slice.
GRANT UPDATE ON public.events TO authenticated;

DO $$
BEGIN
  CREATE POLICY events_update_admin_or_captain
    ON public.events
    FOR UPDATE
    TO authenticated
    USING (
      public.is_claw_admin()
      OR (events.chapter_id IS NOT NULL AND public.is_chapter_role(events.chapter_id, 'captain'))
    )
    WITH CHECK (
      public.is_claw_admin()
      OR (events.chapter_id IS NOT NULL AND public.is_chapter_role(events.chapter_id, 'captain'))
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ===========================================================================
-- 5. chapters UPDATE gate for captains
-- ===========================================================================
-- WHAT: allow an authenticated UPDATE of a chapter row only if the caller is a
--       global admin OR a captain OF THAT chapter (is_chapter_role(id,'captain')
--       — here `id` is chapters.id, the chapter being edited).
-- WHY:  a captain may edit ONLY their own chapter's card (blurb / cover / etc.)
--       from the console; a global admin may edit any. USING + WITH CHECK share
--       the predicate so a captain cannot re-key a row onto a chapter they do
--       not captain. 0002 (§6) granted anon SELECT-only on chapters and NO anon
--       write; that stays true — this GRANT/policy are TO authenticated only, so
--       rls-probe assertion (c) (anon cannot write chapters) STILL HOLDS.
GRANT UPDATE ON public.chapters TO authenticated;

DO $$
BEGIN
  CREATE POLICY chapters_update_captain
    ON public.chapters
    FOR UPDATE
    TO authenticated
    USING (
      public.is_claw_admin()
      OR public.is_chapter_role(chapters.id, 'captain')
    )
    WITH CHECK (
      public.is_claw_admin()
      OR public.is_chapter_role(chapters.id, 'captain')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ===========================================================================
-- 6. rsvps captain-SELECT policy  (roster read for the console + CSV)
-- ===========================================================================
-- WHAT: in addition to 0004's rsvps_select_own (a user sees their OWN rsvps),
--       add a SELECT policy letting a CAPTAIN read the rsvps roster (emails /
--       names) for events IN THEIR OWN CHAPTER only — or a global admin read
--       any roster. This powers the captain console's attendee roster + CSV
--       export.
-- WHY / PII REASONING: rsvp emails are PII (0004's threat model). 0004 gave anon
--   NO rsvps SELECT, and that is unchanged here — rls-probe assertion (g) (anon
--   cannot read the roster) STILL HOLDS, because this new policy is TO
--   authenticated and is gated on is_chapter_role/is_claw_admin, both false for
--   anon. The EXISTS correlates each rsvp to its event's chapter_id and checks
--   the caller captains THAT chapter (chapter_id IS NOT NULL so an unassigned
--   event's roster is admin-only). Net: a captain sees ONLY their own chapter's
--   roster; an admin sees all; everyone else (incl. anon) sees nothing beyond
--   their own rsvps via rsvps_select_own.
DO $$
BEGIN
  CREATE POLICY rsvps_select_captain
    ON public.rsvps
    FOR SELECT
    TO authenticated
    USING (
      public.is_claw_admin()
      OR EXISTS (
        SELECT 1
          FROM public.events e
         WHERE e.id = rsvps.event_id
           AND e.chapter_id IS NOT NULL
           AND public.is_chapter_role(e.chapter_id, 'captain')
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ===========================================================================
-- 7. (OPTIONAL) ONE-TIME, GUARDED backfill of the existing hardcoded admin
-- ===========================================================================
-- WHAT: seed a single admin membership for the existing hardcoded admin
--       (email 'collin@dabl.club', the lone entry in admin/index.html
--       ADMIN_EMAILS) by joining auth.users on lower(email) and attaching it to
--       the SF chapter (slug='sf'), role='admin', ON CONFLICT DO NOTHING.
-- WHY:  is_claw_admin() (§2.5) replaces the ADMIN_EMAILS allowlist, but the
--       function returns true only if a membership row EXISTS. Without this
--       seed, the moment the allowlist is removed the existing admin would lose
--       access. Seeding their admin membership here keeps them working across
--       the cutover. role='admin' is a GLOBAL grant (is_claw_admin ignores which
--       chapter the row is in), so attaching it to 'sf' is just a placeholder
--       home chapter — it grants global admin, not SF-only powers.
-- GUARDED + IDEMPOTENT, exactly like the 0005 backfill:
--   * Wrapped in DO $$ ... EXCEPTION WHEN insufficient_privilege OR
--     undefined_table THEN RAISE NOTICE ...; so if the hosted SQL console role
--     cannot read the auth schema in this environment, the seed is SKIPPED
--     rather than aborting the structural DDL above. Run it later as a
--     documented manual step in that case.
--   * ON CONFLICT (profile_id, chapter_id) DO NOTHING makes re-applying a no-op
--     (and respects the UNIQUE constraint). If the 'sf' chapter or a matching
--     auth user does not exist, the SELECT yields no rows and nothing is
--     inserted — also a safe no-op.
-- >>> If you maintain MORE than one admin, grant the rest the same way in the
--     SQL console (INSERT a role='admin' membership), then delete ADMIN_EMAILS
--     from admin/index.html. <<<
DO $$
BEGIN
  INSERT INTO public.memberships (profile_id, chapter_id, role)
  SELECT u.id, c.id, 'admin'
    FROM auth.users u
    JOIN public.chapters c ON c.slug = 'sf'
   WHERE lower(u.email) = lower('collin@dabl.club')
  ON CONFLICT (profile_id, chapter_id) DO NOTHING;
EXCEPTION
  WHEN insufficient_privilege OR undefined_table THEN
    -- auth schema not readable / not present in this environment: skip the
    -- admin seed rather than abort. Grant it later as a documented manual step.
    RAISE NOTICE 'memberships admin backfill skipped (auth.users not accessible here); grant the admin membership manually if desired';
END $$;
