-- ===========================================================================
-- ClawCamp — Migration 0007: chapter_follows (real follow) + events.capacity
-- ===========================================================================
-- WHY THIS FILE EXISTS:
--   v1.4.0 ("rbac-and-captains-console") makes "follow a chapter" REAL. Today
--   the Join-Chapter modal in chapters/index.html (~line 916, 963) writes a
--   contacts row tagged form_type='chapter_follow' — i.e. a "follow" is just
--   another sparse row in the 44-column contacts god-table, and the original
--   follower-count read (loadFollowers()) hit
--   contacts?form_type=eq.chapter_follow, a path that returns NOTHING now that
--   v1.0.0 REVOKEd anon SELECT on contacts. This migration creates a dedicated
--   chapter_follows table to replace that hack, and adds events.capacity so the
--   captain console can show headcount-vs-capacity and key waitlist logic off
--   it. It pairs with 0006 (memberships/RBAC) and does NOT touch it; the client
--   wiring (follow/unfollow UI, "My Chapters" on the dashboard, the submit-follow
--   Edge Function) is owned by OTHER v1.4 slices.
--
-- THE PRODUCT MODEL (council notes — "email-first; a follow must work WITHOUT
--   login"):
--   A follow is EMAIL-FIRST: a visitor types an email (and optionally a name)
--   and they are following — NO login required. OPTIONAL account linkage happens
--   when a session exists (profile_id is attached if a logged-in user's id is
--   forwarded), exactly the same posture as rsvps.profile_id in 0004. This is
--   why `email` is NOT NULL and `profile_id` IS nullable.
--
-- THE SECURITY POSTURE / THREAT MODEL (anon is a hostile public client — same
--   paragraph as 0004 §4 / 0005 §3 / 0006 §3):
--   The anon key ships in the browser bundle and is held by an untrusted client.
--   Follow emails are PII. So:
--     * anon gets NO INSERT grant on chapter_follows. The ONLY writer is the
--       submit-follow Edge Function holding the SERVICE-ROLE key. This is the
--       non-negotiable council rule first stated in 0003 and repeated for rsvps
--       in 0004: "never a raw anon INSERT on a new public-write table; writes go
--       through the gateway." rls-probe assertion (l) asserts a raw anon POST to
--       /rest/v1/chapter_follows is DENIED.
--     * anon gets NO SELECT — the email list is PII (same as the rsvps roster).
--     * authenticated may SELECT/DELETE only their OWN follows (by profile_id
--       linkage OR by matching JWT email), powering the dashboard "My Chapters"
--       list and the "unfollow" control. This mirrors rsvps_select_own in 0004.
--
-- DUPLICATE PROTECTION:
--   A PARTIAL UNIQUE index (uq_chapter_follows_active) enforces ONE follow per
--   (chapter_id, lower(email)) — one follow per email per chapter, case-folded
--   via lower(email) so "A@x.com" and "a@x.com" collide. It is modeled directly
--   on uq_rsvps_event_email_active (0004). (There is no soft-delete status here,
--   so the partial WHERE clause is a deletion guard kept for parity with the
--   rsvps pattern and to allow a future status column without reshaping the
--   index; unfollow is a hard DELETE — see §2.)
--
-- CONVENTIONS INHERITED FROM 0001–0006 (kept consistent on purpose):
--   * id uses `bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` — the
--     contacts/events/chapters/rsvps/memberships PK style (NOT bigserial/uuid).
--   * chapter_id is `bigint REFERENCES public.chapters(id)` (matches 0002) and
--     profile_id is `uuid REFERENCES auth.users(id)` (matches rsvps.profile_id /
--     memberships.profile_id).
--   * ON DELETE CASCADE on chapter_id (a follow dies with its chapter);
--     ON DELETE SET NULL on profile_id (deleting the auth user detaches the
--     OPTIONAL linkage but keeps the email-first follow intact) — identical to
--     the rsvps FK posture in 0004.
--   * All DDL is idempotent (CREATE TABLE / INDEX IF NOT EXISTS, ADD COLUMN IF
--     NOT EXISTS, and each CREATE POLICY wrapped in
--     `DO $$ BEGIN ... EXCEPTION WHEN duplicate_object THEN NULL; END $$;`, the
--     guard 0005/0006 use) so re-applying is always a safe no-op.
--
-- APPLIED OUT-OF-BAND: like 0002–0006, this file is applied by an admin in the
--   hosted Supabase SQL console — anon cannot run DDL. scripts/rls-probe.sh is
--   the CI gate that asserts the lockdown from a hostile anon client (no raw
--   anon insert into chapter_follows).
-- ===========================================================================

-- ===========================================================================
-- 1. TABLE: chapter_follows  (one row per follow of a chapter)
-- ===========================================================================
-- WHAT: a follow row. email is required (email-first); name optional;
--       profile_id is an OPTIONAL linkage to auth.users for the "session exists"
--       case. Replaces the contacts?form_type='chapter_follow' hack.
-- WHY:  a real, queryable follow table so a chapter's follower count comes from
--       a REAL count (not the dead anon contacts read) and the dashboard can
--       list a user's followed chapters. See the header product/security notes.
CREATE TABLE IF NOT EXISTS public.chapter_follows (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- matches the repo PK style (NOT uuid, NOT bigserial)
  created_at  timestamptz NOT NULL DEFAULT now(),
  chapter_id  bigint NOT NULL REFERENCES public.chapters(id) ON DELETE CASCADE, -- bigint to match chapters.id (0002)
  email       text NOT NULL,                 -- email-first; a follow works WITHOUT login (council notes)
  name        text,                          -- optional display name
  profile_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL  -- OPTIONAL account linkage; nullable, same posture as rsvps.profile_id
);

-- ===========================================================================
-- 2. INDEXES
-- ===========================================================================
-- WHAT: a PARTIAL UNIQUE index on (chapter_id, lower(email)) enforcing one
--       follow per email per chapter (case-insensitive), plus plain indexes on
--       chapter_id and profile_id.
-- WHY:  the unique index (modeled on uq_rsvps_event_email_active in 0004)
--       prevents duplicate follows; lower(email) folds casing. chapter_id is the
--       per-chapter follower-count / "is this email following?" filter, and
--       profile_id backs the dashboard "My Chapters" read by linkage. The WHERE
--       true clause keeps it a partial index for parity with the rsvps pattern
--       and leaves room for a future status column without reshaping the index.
--       All idempotent.
CREATE UNIQUE INDEX IF NOT EXISTS uq_chapter_follows_active
  ON public.chapter_follows (chapter_id, lower(email))
  WHERE true;
CREATE INDEX IF NOT EXISTS idx_chapter_follows_chapter_id ON public.chapter_follows (chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_follows_profile_id ON public.chapter_follows (profile_id);

-- ===========================================================================
-- 3. RLS + GRANTS on chapter_follows  (anon is a hostile public client — same
--    threat model as 0004 §4 / 0005 §3 / 0006 §3)
-- ===========================================================================
-- The anon key ships in the browser bundle and is held by an untrusted client.
-- Follow emails are PII. The combined effect for chapter_follows:
--   * anon can NEVER write — NO INSERT grant. The ONLY writer is the
--     submit-follow Edge Function (service-role key). Non-negotiable council
--     rule: "never a raw anon INSERT on a new public-write table; writes go
--     through the gateway."
--   * anon can NEVER read — NO SELECT grant, NO anon SELECT policy (emails PII).
--   * authenticated may SELECT/DELETE only their OWN follows (linkage OR JWT
--     email), powering "My Chapters" + the unfollow control.
--   * the service role (Edge Function) bypasses RLS for inserts.
-- ===========================================================================

-- WHAT: enable RLS on chapter_follows so the policies below are enforced.
-- WHY:  RLS-on + no anon grant is what makes the follow list unwritable AND
--       unreadable to anon; the service role bypasses RLS so the Edge Function
--       still writes fine.
ALTER TABLE public.chapter_follows ENABLE ROW LEVEL SECURITY;

-- WHAT: ensure anon holds NO table privileges on chapter_follows (defensive
--       REVOKE).
-- WHY:  the non-negotiable rule — no raw anon INSERT, and no anon read of PII
--       emails. We never GRANT anon anything, and REVOKE ALL defensively in case
--       a default/blanket grant exists. So a hostile anon POST is denied
--       (rls-probe assertion (l)) and a hostile anon SELECT returns nothing.
REVOKE ALL ON public.chapter_follows FROM anon;

-- WHAT: authenticated may SELECT only their OWN follows.
-- WHY:  the dashboard "My Chapters" lists the signed-in user's followed
--       chapters. A row is "yours" if its profile_id matches your auth.uid()
--       (the linked-account case) OR its email matches the email claim in your
--       JWT (the email-first case where you later sign in with the same
--       address). Case-insensitive on email to match the unique index. Directly
--       mirrors rsvps_select_own (0004). anon is unaffected (no grant, no
--       policy).
GRANT SELECT ON public.chapter_follows TO authenticated;
DO $$
BEGIN
  CREATE POLICY chapter_follows_select_own
    ON public.chapter_follows
    FOR SELECT
    TO authenticated
    USING (
      profile_id = auth.uid()
      OR lower(email) = lower(auth.jwt() ->> 'email')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- WHAT: authenticated may DELETE only their OWN follows.
-- WHY:  the "unfollow" control removes a follow for a logged-in user on their
--       own row(s), matched by linkage OR JWT email (same predicate as the
--       SELECT policy). anon gets NO delete path. Inserts still go ONLY through
--       the service-role Edge Function — there is intentionally NO authenticated
--       INSERT/UPDATE grant or policy here.
GRANT DELETE ON public.chapter_follows TO authenticated;
DO $$
BEGIN
  CREATE POLICY chapter_follows_delete_own
    ON public.chapter_follows
    FOR DELETE
    TO authenticated
    USING (
      profile_id = auth.uid()
      OR lower(email) = lower(auth.jwt() ->> 'email')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ===========================================================================
-- 4. events.capacity  (headcount cap for the console roster + waitlist logic)
-- ===========================================================================
-- WHAT: add a nullable integer `capacity` column to events. NULL = no cap /
--       unlimited (the default for every existing row, which is why it is
--       nullable — existing rows are unaffected by the ADD COLUMN).
-- WHY:  the captain console roster shows headcount vs capacity, and waitlist
--       logic keys on it (when active RSVPs reach capacity, further RSVPs go to
--       the 'waitlist' status the rsvps table already supports — see 0004). Kept
--       nullable + idempotent (ADD COLUMN IF NOT EXISTS) so applying this is a
--       safe, non-breaking change.
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS capacity integer;  -- nullable; NULL = unlimited
